### PR TITLE
DQ button sequence #786

### PR DESCRIPTION
**Pull request by lainsworth8801**
1. Both 'Restore rules' and 'Reset rules' automatically save changes (without clicking on 'Save');
2. Clicking on 'Save' should uncheck both 'Restore' and 'Reset' because only rules other than those made by 'Restore' or 'Reset' need to be saved. However, clicking on 'Save' should not affect previously saved setting (restore or rest);
3. Clicking on either 'Restore' or 'Reset' should uncheck 'Save' so checkmark indicates which button has been previously clicked on ('Restore' or 'Reset');
4. Clicking on 'Restore' should uncheck 'Reset' and vice versa:

Make a change (error -> warning) and save changes:
Screen Shot 2019-12-10 at 11 09 20 AM

Reset rules. Reset button automatically saves changes. Previously made change is back from 'Warning' to 'Error'. And check mark on 'Save' button disappears:
Screen Shot 2019-12-10 at 11 10 56 AM

Do another change rules (first 2 rules changed, error -> warning) and save changes:
Screen Shot 2019-12-10 at 11 15 49 AM

Now click on 'Restore rule', Check marks on 'Save changes' buttons disappears. Rule restored:
Screen Shot 2019-12-10 at 11 14 33 AM

### CODE REVIEW

**Comment by nllong** [comment]
@lainsworth8801 what issue is this fixing? Is it #786 ?

**Comment by lainsworth8801** [comment]
Yes #786

**Comment by nllong** [comment]
Okay, it appears that #786 also referenced #1848. Do you want to implement that in this PR as well, or is that coming in a separate PR? Just want to check.

**Comment by lainsworth8801** [comment]
I was gonna work on them separately but can definitely merge them together seems easier that way anyway.

**Comment by nllong** [comment]
Let me know which way you want to do it. I can review and merge this one independently, just want to make sure.

Da: Lin Ainsworth <notifications@github.com>
Risposta: SEED-platform/seed <reply@reply.github.com>
Data: martedì dicembre 10 2019 17:07
A: SEED-platform/seed <seed@noreply.github.com>
Cc: Nicholas Long <Nicholas.Long@nrel.gov>, Comment <comment@noreply.github.com>
Oggetto: Re: [SEED-platform/seed] DQ button sequence #786 (#2040)


I was gonna work on them separately but can definitely merge them together seems easier that way anyway.

**Comment by nllong** [comment]
@lainsworth8801 -- Did you mean to close this?

**Comment by lainsworth8801** [comment]
not yet. I'm combining the 2 features and am working on the #1848

**Pull request closed without merging**
