### PR TITLE
Piper/issue 434 labels modal

### PR DESCRIPTION
**Pull request by pipermerriam**
### What does this do?

This incorperates the migrations that were created by @StephenCzarnecki setting up the ManyToMany relationship between CanonicalBuildings and Labels as well as converting the building search functionality to work correctly with the new database schema.

Update:

In addition, this also makes bulk updating work.

#### Cute Animal Picture

ttaracj

### CODE REVIEW

**Comment by pipermerriam** [comment]
Just pushed one more commit that makes bulk updating work.

**Comment by pipermerriam** [comment]
Just pushed 4 more commits to this that remove dead code related to the previous label functionality associated with projects.

**Comment by danielmcquillen** [comment]
FYI, my migrations ran fine after merge:

Running migrations:
  Applying seed.0004_noncanonicalprojectbuildings... OK
  Applying seed.0005_auto_20151201_1510... OK
  Applying seed.0006_canonicalbuilding_labels... OK
  Applying seed.0007_auto_20151201_1515... OK
  Applying seed.0008_remove_projectbuilding_status_label... OK
  Applying seed.0009_merge... OK

**Comment by pipermerriam** [comment]
As for the test failures.  I fixed the ones that make sense.  However, I'm seeing a weird one that I don't understand.

https://travis-ci.org/SEED-platform/seed/builds/94753562#L2450

I don't necessarily think you need to wait for it to be fixed to be merged.  I'll work on figuring out what's going on with it.

**Pull request merged**
