### PR TITLE
update filter AND OR placeholder text

### PR DESCRIPTION
**Pull request by kflemin**
On Inventory List page, Update placeholder text on "AND" and "OR" filters to be more intuitive.
Screenshot 2024-08-08 at 3 44 06 PM

Relevant Ticket: #4737

### CODE REVIEW

**Comment by kflemin** [comment]
@RDmitchell what do you think of the placeholder text in the screenshot above? Let me know if you'd like me to change the wording

**Comment by perryr16** [comment]
Just a thought, would we also want to change the exclude label placeholder? Something like "Exclude all selected labels".

**Comment by RDmitchell** [comment]
@perryr16 -- I think your suggestion of adding the extra text to Exclude would be good, if it's not too late. And if it is too late, no worries, just leave it as is for now !

**Review by perryr16 — APPROVED** [review]
🏆

**Pull request merged**
