### PR TITLE
Feat/inventory summary

### PR DESCRIPTION
**Pull request by laurenliz22**
#### Any background context you want to provide?
Summarizing the count for each of the columns from the "Columns Setting" Tab in the Property Tab 

#### What's this PR do?
Summarizes the count for each of the columns from the "Columns Setting" Tab in the Property Tab.  The columns are the PropertyState column data and include extra data columns that a user will add

#### How should this be manually tested?
Look at the Summary tab of the Property Inventory list to make sure it is aggregating correctly and looks ok.  The files updated include:

seed/static/seed/scss/style.scss
seed/static/seed/js/controllers/inventory_summary_controller.js
seed/static/seed/partials/inventory_summary.html
seed/static/seed/partials/inventory_nav.html
seed/views/v3/analyses.py

#### What are the relevant tickets?
#2806: https://github.com/SEED-platform/seed/issues/2806

### CODE REVIEW

**Comment by Ryoken** [comment]
When there aren't any values in the state's fields, the page errors out and fails to load.  Here are some screenshots showing the debug I used to trace it down:

inventory_summary_controller.js debug:
Screen Shot 2022-02-28 at 3 24 23 PM

resulting output showing energy, property_types, square_footage and year_built are empty arrays:
Screen Shot 2022-02-28 at 3 21 52 PM

Here is the output of the arrays being built in v3/analyses.py:275-293:
Screen Shot 2022-02-28 at 3 24 31 PM

I believe this is happening with this specific data because the related columns were not mapped correctly on import and instead got stuck in extra_data, but this page should be able to account for empty lists either way.

**Comment by Ryoken** [comment]
The actual table added appears to load regardless, and shows the counts correctly!
Screen Shot 2022-02-28 at 4 13 08 PM

**Review by nllong — APPROVED** [review]
Worked for me!
image

**Comment by Ryoken** [comment]
I went ahead and handled cases where there was insufficient data, removing the errors and the empty chart.  While I was there I cleaned up the HTML and CSS a little:

Screen Shot 2022-03-10 at 7 35 54 PM
Screen Shot 2022-03-10 at 7 35 35 PM

**Review by Ryoken — APPROVED** [review]

**Review by nllong — APPROVED** [review]
Looks great! Thanks for the cleanup Ryo.

Also, we can probably close (without merging) this PR #2826.

**Pull request merged**
