### PR TITLE
2690 feat/add annual peak electricity reduction

### PR DESCRIPTION
**Pull request by Ryoken**
#### What's this PR do?
Adds AnnualPeakElectricityReduction

#### How should this be manually tested?
Import a BuildingSync property that has AnnualPeakElectricityReduction and see that it's been added under scenarios in on the property detail page, or inspect the database (see screenshots)

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/2690

#### Screenshots (if appropriate)
Screen Shot 2021-06-03 at 10 31 27 AM
Screen Shot 2021-06-02 at 4 36 01 PM

### CODE REVIEW

**Review by adrian-lara — COMMENTED** [review]
I'm not super knowledgeable in this section of the codebase, but the code changes look reasonable. @macintoshpie tagging you hear in case you have a sec for a quick pass. 

@Ryoken can you provide a test file for me to manually test this?

**Comment by Ryoken** [comment]
> I'm not super knowledgeable in this section of the codebase, but the code changes look reasonable. @macintoshpie tagging you hear in case you have a sec for a quick pass.
> 
> @Ryoken can you provide a test file for me to manually test this?

@adrian-lara seed/seed/building_sync/tests/data/buildingsync_ATT_export.xml should work for testing!

**Comment by adrian-lara** [comment]
> @adrian-lara seed/seed/building_sync/tests/data/buildingsync_ATT_export.xml should work for testing!

Thanks! The new field shows up on the detail page for me 👍🏽 

@macintoshpie I'll still defer to you for approval.

**Review by macintoshpie — APPROVED** [review]
Looks great!

**Pull request merged**
