### PR TITLE
Handle type casting in data quality checks

### PR DESCRIPTION
**Pull request by nllong**
#### Any background context you want to provide?
The typecasting within the data quality checks were not handling the case where a string was defined as a number and has a min/max. This caused the data quality checks to fail ungracefully preventing future checks to occur

#### What's this PR do?
* Update the minimum_valid and maximum_valid checks to correctly handle an invalid typecasting call.
* Add tests

#### How should this be manually tested?
Test 1:
* Modify the data quality rule of a text non-extra-data field (e.g. Address Line 1) so that the rule data type is set to Number, Date, Year, Area, or EUI and it has a minimum and/or maximum value set
* Upload the file and proceed to the Mapping Review screen where data quality results are loaded

Test 2:
* Set an EUI min and max with the unit being either Number or EUI.
* Verify that the DQ's run and report issues appropriately.

Test 3:
* Set the units of the site EUI field to feet squared. This makes no sense, but SEED needs to handle this nicely
* Run a DQ on a record and verify that the DQ results in a warning about mismatched dimensions.

#### What are the relevant tickets?
#1817 
#1845 
#1873 
#1375 (alex)

### CODE REVIEW

**Comment by nllong** [comment]
This may have been resolved with this PR as well: https://github.com/SEED-platform/seed/issues/1511

**Comment by axelstudios** [comment]
@nllong The tests all look good, and I've added a couple of commits with further improvements (see commit messages for details)

That said I'm seeing some really weird behavior when I go back and forth from the Mapping screen to the Mapping Review screen (to review data quality results).  When I change what field I'm mapping to frequently the field disappears entirely, even when switching it between properties/taxlots

**Comment by nllong** [comment]
I think the weird behavior of the data clearing out is as expected. The results of cleansing is stored in redis and I know that we’ve had issues with data not clearing out and getting redundant results. The other reason could be the cache/redis is timing out. 

I’ll test your last changes and merge if all good. Unless you think the issue is a showstopper.

**Comment by axelstudios** [comment]
Test my changes and then we can probably merge this.  The other problem isn't strictly data quality, so it can be a new issue.  I definitely think we should be able to review mapping results, go back and change something, and have it continue to work

**Comment by nllong** [comment]
Yeah it should continue to work, but it would require rerunning the mapping results.

**Comment by axelstudios** [comment]
Hmm, I didn't know it wasn't doing that.  It's definitely re-running data quality checks each time (I'm using always-eager fwiw)

**Pull request merged**
