### PR TITLE
Fixes for data export

### PR DESCRIPTION
**Pull request by pipermerriam**
https://github.com/SEED-platform/seed/issues/732

### What was wrong?

The data export had multiple places where it was broken.

* Incermenting of the progress key wasn't working correctly in most cases.
* The queries it was using weren't up to date with the latest search logic that was implemented.

### How was it fixed.

* Converted the relevant pieces of code to use the new search functions that were recently developed with the label feature.
* Fixed the callback that updates the progress key to update the correct fields.

#### Cute animal picture

16-too-small-cat-in-christmas-turtleneck

### CODE REVIEW

**Comment by pipermerriam** [comment]
Ok, this should be fixed now.  I also fixed another bug that may have been related to one of the other export bugs.  Ready to merge when tests are passing.

**Comment by pipermerriam** [comment]
Weird test failure.  Investigating.

**Comment by pipermerriam** [comment]
Resolved.

**Comment by RDmitchell** [comment]
great !! thx

**Comment by pipermerriam** [comment]
This will also fix https://github.com/SEED-platform/seed/issues/744

**Pull request merged**
