### PR TITLE
Add derived columns to program setup

### PR DESCRIPTION
**Pull request by haneslinger**

### CODE REVIEW

**Comment by kflemin** [comment]
can you double check my fix? derived cols were not evaluating in the compliance calcs on the insights pages b/c they don't have a numeric datatype...this is meant to fix that and was working for me.

**Review by kflemin — APPROVED** [review]

**Comment by RDmitchell** [comment]
@kflemin / @haneslinger -- is there an issue associated with this PR?

**Comment by kflemin** [comment]
I don't think so

**Comment by RDmitchell** [comment]
@kflemin -- I don't really understand what this PR does -- does Program refer to making a program in Insights, so that now it is possible to have derived columns in those definitions?

**Comment by RDmitchell** [comment]
@kflemin -- never mind. I think I understand. 

I have created a derived column, called TotalSiteEnergy, and I now see it in the list of fields when defining the energy metric in an Insights program.

image
image

**Pull request merged**
