### PR TITLE
Data cleansing dialog

### PR DESCRIPTION
**Pull request by axelstudios**
After merging this PR, developers will have a couple changes that are required.

1. Make sure the TOS git checkout is not in SEED/src. For a completely clean checkout you can run `git clean -ffxd`. Make sure that you place two f's. Doing this will remove local_untracked.py and other ignored files/directories (make sure to backup and restore).
1. Run `pip install -r requirements/local.txt`. If there are still issues with dependencies then remove all dependencies and reinstall. To remove all dependencies run `pip freeze | grep -v "^-e" | xargs pip uninstall -y`
1. Update the bower dependencies (lodash was added)
`$ bin/install_javascript_dependencies.sh`
1. Set the `DJANGO_SETTINGS_MODULE` environment variable in `.bashrc` or temporarily in your shell

    ```bash
    # At the end of ~/.bashrc
    export DJANGO_SETTINGS_MODULE=config.settings.dev

    # Directly with the celery command
    DJANGO_SETTINGS_MODULE=config.settings.dev celery -A seed worker -l info -c 4 --maxtasksperchild=1000 --events
    ```
1. Celery is now a command line argument (no more ./manage.py celery). To start celery after the upgrade run `celery -A seed worker -l info -c 4 --events --maxtasksperchild 1000`
1. In your existing local_untracked.py make sure to remove the line which sets up celery `djcelery.setup_loader()`.

### CODE REVIEW

**Comment by cycustodio** [comment]
Alex, 
I pulled the branch on the development environment to confirm the instructions. At step 4, I'm getting the following error: 
```ImportError: Could not import settings 'config.settings.main' (Is it on sys.path? Is there an import error in the settings file?): No module named aws```
There is an aws folder and python file in config/settings.  

Also, doing step 1 deleted the src directory, was that supposed to happen?  

Thanks.

**Comment by RDmitchell** [comment]
I would like to demo this somehow (hopefully through seedtest.lbl.gov) at 9 am this coming Wednesday, 9/14/2015 at the mid-month SEED user meeting. 

It may not be possible to do this, but if we can get it tested and moved over to seedtest by tomorrow sometime (Tuesday) so that I can see how it works, that would be great. 

If this isn't happening by tomorrow mid-afternoon, I will punt and talk about something else. I just need a bit of lead time to either learn how this works so I can demo it, or figure something else out. 

Thanks Robin

**Comment by axelstudios** [comment]
@cycustodio Sorry, there's an environment variable that needs to be set to tell Django which configuration you want to run in (added these notes above):
`DJANGO_SETTINGS_MODULE=config.settings.dev`

There are a couple ways to set it - either in .bash_profile/.bashrc, or directly with the command.  Personally, I created a celery.sh script with the following:
```bash
DJANGO_SETTINGS_MODULE=config.settings.dev celery -A seed worker -l info -c 4 --maxtasksperchild=1000 --events
```

**Comment by cycustodio** [comment]
Thanks for clarifying. I will try that.

**Comment by nicholasserra** [comment]
@RDmitchell @mmclark can we send out a mass email any time environment changes are introduced? Would be convenient, as opposed to looking through history and pull requests to find out.

**Comment by RDmitchell** [comment]
Yes we were going to do it and didn't.

**Comment by RDmitchell** [comment]
This looks good as the initial cut for data cleansing.

**Comment by nicholasserra** [comment]
I'm suddenly getting errors from this Cleansing model while running tests. Looks like a migration might be missing when this was implemented? I see the new model declared, but I don't see a migration for the table.

**Comment by nllong** [comment]
Look at this branch: https://github.com/SEED-platform/seed/tree/remove-cleansing-model.

**Comment by nicholasserra** [comment]
+1 on that

**Comment by nllong** [comment]
@nicholasserra can you merge it into your branch and test it. I don't get a cleansing migration error on my local dev, so I'm hoping that it fixes your issue.

**Comment by nicholasserra** [comment]
@nllong I checked out your branch and it works for me :D I'd say go ahead and merge it into develop.

**Pull request merged**
