### PR TITLE
Allow switching cycles in inventory detail page

### PR DESCRIPTION
**Pull request by haneslinger**
#### What are the relevant tickets?
#3767

#### Screenshots (if appropriate)
image

### CODE REVIEW

**Comment by RDmitchell** [comment]
Great addition !!

**Comment by haneslinger** [comment]
@axelstudios might you know why this test is failing?

**Review by anchapin — CHANGES_REQUESTED** [review]
This looks good and I can't see any functional issues with it. I have two minor requests though.

1. Make it so that the cycle dropdown doesn't extend to the right past the "Detail Column List Profile:" dropdown.
2. Sort the cycles in the dropdown to be in alphabetical order. (refer to image below to see that in my case 2020 appears below 2022 and 2023)

image

**Comment by haneslinger** [comment]
> Sort the cycles in the dropdown to be in alphabetical order. (refer to image below to see that in my case 2020 appears below 2022 and 2023)

done

> Make it so that the cycle dropdown doesn't extend to the right past the "Detail Column List Profile:" dropdown.

I don't quite understand. you what it to take up less horizontal space?

**Comment by anchapin** [comment]
> > Make it so that the cycle dropdown doesn't extend to the right past the "Detail Column List Profile:" dropdown.
> 
> I don't quite understand. you what it to take up less horizontal space?

Yes, to me it looks strange that the cycle dropdown is so large horizontally. It's not a big deal but I thought if the right side of the cycle dropdown aligned with the right side of the "Detail Column List Profile:" dropdown that it would look better.

**Review by anchapin — APPROVED** [review]
Thank you for making those changes!

**Pull request merged**
