### PR TITLE
954 - Added selenium test to check year ending can be edited.

### PR DESCRIPTION
**Pull request by tallus**
- made generic wait_for_element method take can use different
      strategies
    - converted wait_for_element_by_css to use this
    - added set_buildings_list_columns method to control displayed
      columns in buildings list
#### Any background context you want to provide?
This is a test for #953.  Could not reproduce issue but added test to ensure it works.
#### What's this PR do?
Adds a Selenium test against this issue. Expanded functional test functionality.
#### How should this be manually tested?
No need to manually test as this adds automated test
#### What are the relevant tickets?
 #953
#### Definition of Done:
- [x] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [x] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)

### CODE REVIEW

**Comment by RDmitchell** [comment]
Paul -- thanks for getting a selenium test going for this !

**Comment by nllong** [comment]
👍

**Comment by RDmitchell** [comment]
should this be merged just into develop or also into the "release-1.5.0" branch? 

just wanted to make sure we get it in all the needed places.

**Comment by nllong** [comment]
Merge into develop. It will appear in 1.5.0 when the two other PRs are
merged.

**Comment by RDmitchell** [comment]
perfect, thanks !

**Pull request merged**
