### PR TITLE
Updates 'Edit Columns' button and related help text to 'View/Hide Column...

### PR DESCRIPTION
**Pull request by danielmcquillen**
Updated the 'Edit Columns' buttons to show 'View/Hide Columns' on the mapping.html and matching.html partials. Also updated related help text in same files. Fixes issue #52. (Sorry that should have been in commit message.)

### CODE REVIEW

**Comment by RDmitchell** [comment]
Things are not quite right in the implementation of this feature. See the screen shot below. I don't know if this is an issue with how it was merged into the LBL instance, or an issue with the original implementation. I am testing on the LBL seedtest instance. I can give you an account on that instance so you can see the issue.

image

**Comment by meghasandesh** [comment]
This is a merge conflict.

Daniel,

Could you pull in the latest develop branch and do a new pull request after
fixing the conflicts?

Thanks

Megha

**Comment by cycustodio** [comment]
Also, two "Save Mapping" buttons at the top.


----------------------------------------------------------------
Claudine Y. Custodio
cycustodio@lbl.gov
510-495-8062 (Office)
Energy Technologies Area
Lawrence Berkeley National Lab
-----------------------------------------------------------------

**Comment by meghasandesh** [comment]
Same issue. If you notice anything else out of place, it is probably going
to be related to the conflict.

**Comment by danielmcquillen** [comment]
I've done a new pull request with a fix for those merge comments.

**Comment by RDmitchell** [comment]
Fixed and tested on seedtest. Ready for production.

**Pull request merged**
