### PR TITLE
Issue #492 - Exclude filters

### PR DESCRIPTION
**Pull request by nicholasserra**
#### What's this PR do?
Adds ability to filter by excluding words.

#### What are the relevant tickets?
Refs #492

### CODE REVIEW

**Comment by rebrownlbnl** [comment]
Is there any guidance for the users about how to use this functionality? (or any of the other filtering capabilities we've added in the last couple months, for that matter)

**Comment by nicholasserra** [comment]
I don't know if there are docs around this at all. @RDmitchell probably has an idea.

**Comment by RDmitchell** [comment]
I have a doc on the seed website about filtering, but it would be nice to incorporate that info into the program with help icons or something. This is something I will probably give to @danielmcquillen  to work on this Spring, ie, getting help information better incorporated into the program

**Comment by RDmitchell** [comment]
this page has a link to the current "filtering" documentation
http://seedinfo.lbl.gov/detailed-support

**Comment by RDmitchell** [comment]
@nicholasserra -- what did you end up implementing for this?

**Comment by nicholasserra** [comment]
To exclude a piece of text, use an exclamation point at the begging with no quotes. aka `!exclude`

**Comment by nicholasserra** [comment]
Or wrap in quotes for exact exclude `!"ExClUdE"`

**Pull request merged**
