### PR TITLE
Feat/fix merge option

### PR DESCRIPTION
**Pull request by Ryoken**
#### Any background context you want to provide?
see https://github.com/SEED-platform/seed/issues/2624 and https://github.com/SEED-platform/seed/issues/2410

#### What's this PR do?
re-enables manual merging and preserves the original "updated" order

#### How should this be manually tested?
Find three properties that may be merged and trigger a manual merge while looking at the middle property, chronologically.  This property should not be the primary property after merged.

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/2624

### CODE REVIEW

**Comment by Ryoken** [comment]
@adrian-lara -- what we decided on our call this morning was to keep the button disabled for the March 31 release, and move this issue to the next release cycle, and then decide on the full functionality to be implemented, which hopefully will include the ability of the user to "ok" the new order or change it if needed, in a similar manner to how this works in the list view. Thanks !!

_Originally posted by @RDmitchell in https://github.com/SEED-platform/seed/issues/2624#issuecomment-806034883_

**Comment by nllong** [comment]
One year later and we should decide if this should be enabled for this coming release? What do you think @Ryoken and @RDmitchell?!

**Comment by Ryoken** [comment]
I am good to merge as-is, even without the confirmation.

**Comment by nllong** [comment]
> I am good to merge as-is, even without the confirmation.

sounds good. Can you resolve the conflicts? They look small..

**Comment by Ryoken** [comment]
Resolved and ready to go!

**Comment by nllong** [comment]
Looks like the tests are failing, probably due to ordering... https://github.com/SEED-platform/seed/runs/5603891653?check_suite_focus=true#step:10:408

**Comment by RDmitchell** [comment]
What merging are we talking about? Is it the merging of properties in the list view and unmerging in the Detail view? 

Or something else?

**Review by perryr16 — APPROVED** [review]

**Pull request merged**
