### PR TITLE
BuildingSync Asset Extractor Functionality

### LINKED ISSUE #3200: BuildingSync Asset Extractor Integration

### PR DESCRIPTION
**Pull request by kflemin**
#### What's this PR do?
This PR implements the BAE functionality in seed automatically on buildingsync file imports

#### How should this be manually tested?
- Run database migrations
- Import a BuildingSync file and notice the assets extracted and mapped

#### What are the relevant tickets?
Resolves #3200
#### Screenshots (if appropriate)
Screen Shot 2022-04-18 at 12 23 13 PM

### CODE REVIEW

**Comment by kflemin** [comment]
@Ryoken, if you have the time to review this PR, could you take a look at the failing tests? I'm not sure why they are failing / what I changed that would cause them to fail.  thanks!

**Comment by kflemin** [comment]
@nllong, the tests are finally passing!!🎉
Except for that last one pre-commit.ci - pr....not sure what that's about?

**Comment by kflemin** [comment]
@nllong wooot!!!  Should we wait to merge until I have the real assets mapped in BAE? Or merge and make a new branch for the upcoming work?

**Comment by nllong** [comment]
i say we merge, then add in the new assets with new tickets.

**Comment by kflemin** [comment]
@nllong sounds good to me! i'll let you do the honors :)

**Pull request merged**
