### PR TITLE
Forgo evil evil serializer

### PR DESCRIPTION
**Pull request by haneslinger**
#4433

### CODE REVIEW

**Review by kflemin — APPROVED** [review]

**Comment by kflemin** [comment]
did it speed it up?

**Comment by haneslinger** [comment]
I created ~100 output_files. The old code ran in ~1 sec, the new in <1 sec. negligible with that number of rows. However, the end point use to run a query for each analysis_property_view/AnalysisOutputFile pair, which accounted for the bulk of the run time. and now it's done in a single query.

It's worth noting this endpoint is still probably returning more data than needed, but this should address the main problem.

**Comment by RDmitchell** [comment]
@haneslinger -- you can test using the BPS Test - DC org -- it has 3,000+ records

**Comment by haneslinger** [comment]
It's a pain to get a prod db on my local instance and it makes testing really time consuming. If @kflemin thinks it beneficial to run more test before merging I can, but I think it might be best to simply get the change to prod quickly.

That said, @axelstudios said "[BPS Test - DC org] seed_analysisoutputfile_analysis_property_views has 869 rows". I have 52 locally. If BPS Test - DC org take 5 min, you'd think mine would take at least 10 sec?

ugh, let my see if the "parsed data" field is good to be removed. that'll cut down on the size.

**Comment by RDmitchell** [comment]
@haneslinger -- no worries -- I'll test when this is deployed to dev1 !!

**Comment by haneslinger** [comment]
right-o, removed "parsed_results", didn't need it. decimated the size of the response.

**Pull request merged**
