### PR TITLE
Fix legend

### PR DESCRIPTION
**Pull request by haneslinger**
#### What are the relevant tickets?
#3665
#### Screenshots (if appropriate)
image

WARNING: it can still look pretty wild with the right configs.
image

### CODE REVIEW

**Comment by isalanglois** [comment]
@haneslinger can you add a label on this PR?

**Review by anchapin — COMMENTED** [review]
I'm getting the label name change as expected but some reason it's not in alphabetical order anymore.

image

I'm not sure why though, that part of the code is still in there.

**Comment by haneslinger** [comment]
> I'm getting the label name change as expected but some reason it's not in alphabetical order anymore.
> 
> image
> 
> I'm not sure why though, that part of the code is still in there.

Hard reload the browser maybe?

**Comment by haneslinger** [comment]
@anchapin I think I fixed it!

**Pull request merged**
