### PR TITLE
Add to CTS button

### PR DESCRIPTION
**Pull request by haneslinger**
image

### CODE REVIEW

**Comment by RDmitchell** [comment]
just for my edification, what does "export to CTS" do?

**Comment by haneslinger** [comment]
@laurenliz22 ESTP project requested the ability to export seeds buidingsync files into this very specific file format.

**Review by kflemin — COMMENTED** [review]
when I try to run this, I get a 500 on this call:
2024-05-29 13:54:34 ERROR    "POST /api/v3/tax_lot_properties/export_to_cts/?organization_id=1 HTTP/1.1" 500 26363

File "/Users/kflemin/repos/seed/seed/views/v3/tax_lot_properties.py", line 697, in export_to_cts
    building_sync_to_cts(list(building_files), Path(f.name))
  File "/Users/kflemin/.pyenv/versions/newseedenv/lib/python3.9/site-packages/buildingsync_asset_extractor/cts/cts.py", line 66, in building_sync_to_cts
    facility_by_id = aggregate_facilities(files)
  File "/Users/kflemin/.pyenv/versions/newseedenv/lib/python3.9/site-packages/buildingsync_asset_extractor/cts/cts.py", line 36, in aggregate_facilities
    file_etree = etree.parse(f)
  File "src/lxml/etree.pyx", line 3538, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1899, in lxml.etree._parseDocument
TypeError: cannot parse from 'dict'

I do know that this property has a buildingsync file that does not contain a facility ID...perhaps we just need to handle that error better?

**Comment by haneslinger** [comment]
how odd, can we look at it together tomorrow?

**Review by kflemin — APPROVED** [review]
🏆

**Pull request merged**
