### PR TITLE
Issue 8 - show green button file

### PR DESCRIPTION
**Pull request by philngo**
- Added an Energy tab to building detail page which shows the names of any uploaded and matched XML files.
- Added GREEN_BUTTON_BS to the list of acceptable ancestors in `get_ancestors` (used in the `get_building` API function), which shows green button files on the building info tab

### CODE REVIEW

**Comment by rebrownlbnl** [comment]
Do the changes to models.py require a database migration?

**Comment by philngo** [comment]
No, they don't.

**Comment by mmclark** [comment]
Phil - there are currently some merge conflicts.  Could you clear these up and re-issue the pull request?  Thanks!

**Comment by philngo** [comment]
#Should clear up the conflicts. Sorry about that!

**Pull request closed without merging**
