### PR TITLE
Add transactions

### PR DESCRIPTION
**Pull request by nllong**
#### Any background context you want to provide?
Working on speeding up data ingestion and mapping merging.

On first import, the majority of the time is spent making the objects in the database. After that, it is calculating which objects are similar. This PR is addressing the former case.

#### What's this PR do?
Wrap transactions around data ingestion and merging.
There is a new migration to create an index to make reading the data much faster.

#### How should this be manually tested?
Lots of monkey testing.

#### What are the relevant tickets?
#1498 
#1565 should be fixed regarding the ascii/unicode character. If #1565 is a different issue, then we should make a new ticket.

#### Definition of Done:
- [x] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [x] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [x] Does this PR require a regression test? All fixes require a regression test.
- [x] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

### CODE REVIEW

**Comment by axelstudios** [comment]
@nllong I'm not seeing any new migrations?

**Comment by axelstudios** [comment]
Here are the preliminary performance results (timed from the user perspective, and starting from the same VM snapshot each time)

## File
22.8 MB xlsx PM file
Total rows: 16,421
Total cols: 257

### Before (develop)
```
Total upload/save_raw_data		 3:00 total
	save_raw_data call		 1:48
Map Your Data				 5:47 total
	perform_mapping			 5:15
	filtered_mapping_results	 0:25
Save Mappings				12:28 total
	matching			 7:47
	pairing				 3:42
	matching_results		 0:59

New properties: 15,785
Merged properties: 317
Resulting rows: 16,102
```
### After (1498-transactions)
```
Upload/save_raw_data			 2:07 total
	save_raw_data			 1:36
Map Your Data				 5:36 total
	perform_mapping			 5:02
	filtered_mapping_results	 0:27
Save Mappings				10:39 total
	matching			 6:16
	pairing				 3:27
	matching_results		 0:56

New properties: 15,785
Merged properties: 317
Resulting rows: 16,102
```

**Comment by nllong** [comment]
Looks like I missed those files. Just pushed them.

**Comment by axelstudios** [comment]
Final performance results:

### After with index (1498-transactions)
```
Upload/save_raw_data			 2:06 total
	save_raw_data			 1:36
Map Your Data				 5:03 total
	perform_mapping			 4:29
	filtered_mapping_results	 0:24
Save Mappings				9:30 total
	matching			 5:39
	pairing				 3:03
	matching_results		 0:48

New properties: 15,785
Merged properties: 317
Resulting rows: 16,102
```

Upload processing: 43% faster
Mapping processing: 15% faster
Matching processing: 31% faster

**Pull request merged**
