### PR TITLE
Updated translation files

### PR DESCRIPTION
**Pull request by axelstudios**
#### What's this PR do?
Updates text on the data upload dialog
#### How should this be manually tested?
Click the button to upload a file and review the text on the first screen.
#### What are the relevant tickets?
#1573
#### Screenshots (if appropriate)
image

### CODE REVIEW

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 51231c0

Looks good !

**Comment by RDmitchell** [comment]
@nllong -- in the Project, in the In Progress, Test and Done columns, only the PRs show up. Shouldn't we also have the issues there? or at least in the Done column? I guess you have automated, this, so maybe only PRs can show up, but when I test, I am closing issues that are referenced in the PR, and I would be happy to add those issues to the Done column in the project "by hand" when I close them ... ???

**Comment by RDmitchell** [comment]
@nllong -- now I see that in the To Do column, the issues are listed. And since I closed issue 1573, which is fixed with PR 1602, the issue shows that it has been closed (red exclamation point).

So I guess as I close issues you will see them go "red" in the To Do column, which may be good enough. 

However, I am also happy to move those closed issues over to the Done column when I close them. 

Just let me know what you want to workflow to be. 

I think it's great that we are just using Github !!! Thanks for setting this all up.

**Comment by nllong** [comment]
Yeah, we should move the issues over when they are closed. Thanks!

**Pull request merged**
