### PR TITLE
Disallow manual merge of records with different alis

### PR DESCRIPTION
**Pull request by haneslinger**
#### How should this be manually tested?
try the merge two things in different alis?

#### Screenshots (if appropriate)
image

### CODE REVIEW

**Comment by RDmitchell** [comment]
what is an alis ?

**Comment by haneslinger** [comment]
@kflemin, do you know why the tests are erroring? It says 
```TypeError: catching classes that do not inherit from BaseException is not allowed```
and I do create new Error but they inherit from Exception.

**Comment by haneslinger** [comment]
> what is an alis ?

Access Level Instances

**Comment by RDmitchell** [comment]
Thx !!

**Review by kflemin — APPROVED** [review]
🏆

**Pull request merged**
