### PR TITLE
Piper/issue 565 revert tax id splitting

### PR DESCRIPTION
**Pull request by pipermerriam**
This is tracked via issue https://github.com/SEED-platform/seed/issues/565 which reverts all of the changes done via:

* Issue https://github.com/SEED-platform/seed/issues/521 / PR https://github.com/SEED-platform/seed/pull/523
* Issue https://github.com/SEED-platform/seed/issues/513 / PR https://github.com/SEED-platform/seed/pull/519
* Issue https://github.com/SEED-platform/seed/issues/480 / PR https://github.com/SEED-platform/seed/pull/487

### What was wrong?

The work done for #480 turned out to not be a viable approach to fixing the problem.  After investigation and numerous problems related to the changes, it was decided to revert these changes.  The decision was made on 2015/12/15 on the 11am MST call with @RDmitchell @StephenCzarnecki and @rebrownlbnl .

### How was it fixed.

Reverted all of the commits.

#### Cute animal picture

pangolin baby portrait

### CODE REVIEW

**Comment by pipermerriam** [comment]
@RDmitchell the failure here is the same firefox failure we've been struggling with.

**Comment by RDmitchell** [comment]
@pipermerriam  -- The cute animal (what is it?) looks like he is ready to tackle the task of reverting code !

**Comment by pipermerriam** [comment]
@RDmitchell id normalization back in via 216a5e3b44b4da385e5a9a44cb75c2ee40252997

**Comment by pipermerriam** [comment]
It's a https://en.wikipedia.org/wiki/Pangolin

**Comment by RDmitchell** [comment]
Ah yes, pangolin. I googled scaly anteater and got to it !

**Pull request merged**
