### PR TITLE
2844 refactor/list analysis

### PR DESCRIPTION
**Pull request by Ryoken**
#### Any background context you want to provide?
see ticket

#### What's this PR do?
Adds a tab to the analyses page that lists all analyses by property, rather than by analysis.

#### How should this be manually tested?
Run analyses on various properties and check the analyses page.

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/2844

#### Screenshots (if appropriate)
Screen Shot 2022-03-28 at 5 10 43 PM

### CODE REVIEW

**Comment by RDmitchell** [comment]
The tabs seem like a nice solution ! Thx !

**Review by perryr16 — COMMENTED** [review]
It seems the "By Analysis" tab has a lot more information. I think it might be useful to have similar info on the "By Property" tab like "analysis name", "created", "run status". Just a thought, happy to discuss. Otherwise it works like a charm

**Review by perryr16 — CHANGES_REQUESTED** [review]
The "By Analysis" tab is sorted from newest to oldest, while "By Property" tab is sorted from oldest to newest. Can you change the sorting of "By Property" to `Run ID` descending?

**Comment by Ryoken** [comment]
> The "By Analysis" tab has a lot more information. I think it might be useful to have similar info on the "By Property" tab like "analysis name", "created", "run status". Just a thought, happy to discuss. Otherwise, it works like a charm

Good point.  We are making a ticket soon to discuss what we want showing up in this table and how to display it.

**Review by haneslinger — APPROVED** [review]
LGTM

**Pull request merged**
