### PR TITLE
Fix building deletion while filtering by label

### PR DESCRIPTION
**Pull request by pipermerriam**
https://github.com/SEED-platform/seed/issues/730

### What was wrong.

The `seed.views.delete_buildings` view was still using the *old* search logic so it didn't work when filtering by labels.

### How was it fixed.

Updated it to use the new search functionality.

#### Cute animal picture

tumblr_np90u2dxgu1qbjrrso7_500

### CODE REVIEW

**Comment by pipermerriam** [comment]
I need some help understanding this code.

```python
    if not body.get('select_all_checkbox', False):
        # only get the manually selected buildings
        selected_buildings = get_search_query(request.user, {})
        selected_buildings = selected_buildings.filter(
            pk__in=selected_building_ids,
            super_organization__in=orgs
        )
    else:
        # get all buildings matching the search params minus the de-selected
        selected_buildings = get_search_query(request.user, body)
        selected_buildings = selected_buildings.exclude(
            pk__in=selected_building_ids,
        ).filter(super_organization=orgs)
```

This code translates into this logic.

* If the *select all* checkbox is **not** checked.
    * delete all of the buildings that were selected individually.
* If the *select all* checkbox is checked.
    * delete all of the buildings except for the ones that were individually checked.  (THIS IS THE WEIRD PART)

This functionality seems wrong.  If the select all checkbox has been selected why wouldn't you delete all of the buildings?  If the idea was that you could use the *select all checkbox* to select all of the buildings and then deselect a few that you didn't want to delete, then this query is actually wrong.

Please advise.  @mmclark it appears you were the original author of this code so maybe you can shed some light.

**Comment by RDmitchell** [comment]
@pipermerriam -- I agree with you -- if the select all checkbox is checked, the program should delete all the checked buildings. This should basically overwrite the original records that were checked by hand. I wouldn't think that @mmclark wrote this code, I would have thought it was original code from BE, but I guess I could be wrong.

**Comment by nicholasserra** [comment]
Yeah that seems like some weird UI thing, where maybe there was a "delete all EXCEPT checked" functionality. I'd rewrite it to what you think is sane.

**Comment by RDmitchell** [comment]
agreed

**Comment by pipermerriam** [comment]
Ok, removing this functionalitiy and the associated test.  Lets see what travis says.

**Comment by rebrownlbnl** [comment]
Could that logic have been used for the use-case where you want to delete all but a few buildings, so you check the "select all" checkbox, then manually unselect the few buildings that you want to keep?

**Comment by pipermerriam** [comment]
> Could that logic have been used for the use-case where you want to delete all but a few buildings, so you check the "select all" checkbox, then manually unselect the few buildings that you want to keep? 

I think that was the intention but it would *unintuitively* keep the buildings you left checked (the unchecked ones would still be deleted).  Very poor UX and major violation of [least astonishment principle](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by RDmitchell** [comment]
agreed -- hadn't ever heard about the LAP, so thanks for the link !!!

**Pull request merged**
