### PR TITLE
3163 fix/differentiate null and missing

### PR DESCRIPTION
**Pull request by Ryoken**
#### Any background context you want to provide?
see ticket

#### What's this PR do?
Updates "recognize_null" to not affect imports where a column is missing.

#### How should this be manually tested?
- Pick a field (ie: energy_star).
- turn "recognize_null" OFF for this field
- import a file with the field present and non-empty, note it's presence on the property
- import another file with the field missing completely, note the value on the property doesn't change
- import another file with the field present and empty, note the property value still doesn't change
- turn "recognize_null" ON for this field
- import a file with the field present and non-empty, note it's presence on the property
- import another file with the field missing completely, note the value on the property doesn't change
- import another file with the field present and empty, note the property value finally changes

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/3163

#### Screenshots (if appropriate)
"recognize_null" OFF... note the value remains
Screen Shot 2022-03-18 at 2 41 14 PM

"recognize_null" ON... note value only changes once the column is BOTH present and empty
Screen Shot 2022-03-18 at 2 31 04 PM
Screen Shot 2022-03-18 at 2 35 58 PM
Screen Shot 2022-03-18 at 2 36 50 PM

### CODE REVIEW

**Comment by nllong** [comment]
I have a feeling that all of the Django test errors are happening because the state2 model is None. I'm wondering if the state1 model is being used by itself at times???

**Comment by Ryoken** [comment]
> I have a feeling that all of the Django test errors are happening because the state2 model is None. I'm wondering if the state1 model is being used by itself at times???

It appears to be that state2 is built by hand and the import files are only populated as needed for that test.  I put in some checks to ensure the sate has what we need before using it.

**Review by nllong — CHANGES_REQUESTED** [review]
Hey @Ryoken  -- i tested this and glad that I tried it with an extra data field. It worked fine with a db-based field, but with an extra data field it just overwrote everything.

I think we need to pass in the import_file columns here https://github.com/SEED-platform/seed/blob/3163-fix/differentiate-null-and-missing/seed/lib/merging/merging.py#L138-L163.

**Comment by Ryoken** [comment]
Ah, good catch!  I will revisit this asap

**Comment by nllong** [comment]
> Ah, good catch! I will revisit this asap

cool thanks. If you get something in before noon on Monday, I'll take a look!

**Comment by nllong** [comment]
The recognize null is now working as expected for both canonical fields and extradata fields; however, it looks like a few tests are failing. I did not investigate those errors but I think they are worth a deep dive to figure out what the right logic should be.

Also, I doubt it is related but the column filters on beta properties is not working on my computer anymore. I'm on safari and it was bypassing the cache.


image

**Pull request merged**
