### PR TITLE
Fix ali tree permissions

### PR DESCRIPTION
**Pull request by haneslinger**

### CODE REVIEW

**Comment by haneslinger** [comment]
oh! yes, thank you

**Comment by perryr16** [comment]
Could you provide some details regarding how this should be tested?

**Comment by haneslinger** [comment]
@perryr16 updated

**Review by perryr16 — DISMISSED** [review]
thanks!

**Comment by haneslinger** [comment]
nice catch! thank you, please add it

**Review by perryr16 — APPROVED** [review]
This is perfect! thank you

**Pull request merged**
