### PR TITLE
[Issue 108] Refreshing page so that concerned fields are updated and the...

### PR DESCRIPTION
**Pull request by meghasandesh**
... modal works as expected

### CODE REVIEW

**Comment by mmclark** [comment]
Merged into testing branch and deployed to seedtest

**Comment by RDmitchell** [comment]
Megha

How do I test this? I'm not sure what the feature is.

Robin

**Comment by meghasandesh** [comment]
Robin,

This is issue #108 - where you can edit columns in the matching screen but
the changes would not save

Megha

How do I test this? I'm not sure what the feature is.

Robin

—
Reply to this email directly or view it on GitHub
<https://github.com/SEED-platform/seed/pull/112#issuecomment-75698138>.

**Comment by RDmitchell** [comment]
This is tested and is working properly. Please move to the production server / public repository.

**Comment by mmclark** [comment]
This PR was issued against master.  It was re-issued against develop per our discussion and has been merged (seed PR #135).  This should be closed.

**Comment by RDmitchell** [comment]
Miles – do you close the pull request or do I?

 

Closing it is fine.

 

Robin

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by mmclark** [comment]
Moving forward, I'll plan on closing them in cases like this.

**Comment by RDmitchell** [comment]
perfect

 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Pull request closed without merging**
