### PR TITLE
Extra error handing for PM template list

### PR DESCRIPTION
**Pull request by Myoldmopar**
#### Any background context you want to provide?
Issue #1583 describes an error where the user got 500 errors when trying to connect to PM.  Looking at Sentry, it looks like the connection to PM was successful, but something bad was coming through in the response.  The templates weren't fully formed.  It's possible the report template isn't well formed on PM or something.

#### What's this PR do?
This PR adds extra error handling to the template response.  Instead of blindly assuming that each template row will have id and name keys, it checks for them explicitly.  If they aren't there, a debug message is thrown, and that template is not included in the list offered to the user to select from.

#### How should this be manually tested?
For well-formed responses, like those I receive on my own machine with our test PM account, this won't change anything.  For responses that fail because of a bad template response, log messages should be thrown, but the user should simply see the list of valid templates.

#### What are the relevant tickets?
#1583

#### Definition of Done:
- [ ] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [ ] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [ ] Does this PR require a regression test? All fixes require a regression test.
- [ ] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

### CODE REVIEW

**Comment by Myoldmopar** [comment]
@nllong does Sentry include the logging output?

**Comment by nllong** [comment]
I don't think Sentry includes the logging output (as in the server logs).
AKAIK it is just the stack trace.

**Comment by RDmitchell** [comment]
@Myoldmopar / @nllong -- once this is settled and on dev1, I can have the user log in to a test account on dev1 and see if this fixes the problem

**Comment by RDmitchell** [comment]
Let me know when this is on dev1 so it can be tested ... thanks !!

**Comment by Myoldmopar** [comment]
So I can think of two options, and maybe both of them need to be done:
1. Change this so that it reports an error that Sentry traps (just raise an exception?)
2. Change the response to the front-end so that it includes an error that the user can address.

I will feel better about deciding whether to include those once I know if the user's issue is addressed by the code changes currently in place.

**Comment by Myoldmopar** [comment]
OK, I added some more error handling, the server side should be extra robust now.

For the front end, I added a warning message, but I'm looking for advice on the message to be shown:
image

I'll push my changes as of now, and we can refine that and @axelstudios can tell me if I already did something wrong on the JS side.

**Comment by RDmitchell** [comment]
thx @Myoldmopar 

what is the "I will keep trying" part? What does that tell the user?

**Comment by Myoldmopar** [comment]
This is really just the difference between errors and warnings.  In this case, the code encounters "errors" in the data coming back from PM, but they may not impact the user's workflow.  So I still want to warn the user about the issues, but that the code is going to continue to run.

**Comment by RDmitchell** [comment]
I'm not sure the text "I will keep trying" conveys to the user what is going on. 

Maybe something like, "I have encountered issues, but you should be able to import your data" or something?

**Comment by nllong** [comment]
@Myoldmopar can we delete this PR?

**Pull request closed without merging**
