### PR TITLE
Final version of the BPS sample data files

### PR DESCRIPTION
**Pull request by anchapin**
#### Any background context you want to provide?
The data is taken from the [Building Energy Benchmarking](https://opendata.dc.gov/datasets/DCGIS::building-energy-benchmarking/about) data set for Washington DC. Nine properties were included with a mix of property types.

#### What's this PR do?
Adds sample data that can be used to upload data into SEED to test BPS functionality.

#### What are the relevant tickets?
#3473

### CODE REVIEW

**Comment by nllong** [comment]
Hey @anchapin  -- what is remaining on this? Can we merge and update the data on our instances?

**Comment by anchapin** [comment]
> Hey @anchapin -- what is remaining on this? Can we merge and update the data on our instances?

@nllong I'm just waiting on someone to review at this point.

**Comment by nllong** [comment]
@anchapin  -- what is the order to load this data? Maybe we should put the BPS data in its own folder with a README.md to let others know how to import? 
image

**Comment by anchapin** [comment]
@nllong I like your suggestion for having the data in its own folder with a readme.md. I can try to work on this when I have time.

**Comment by nllong** [comment]
Can you give me the quick list and I'll write it up? I want to import this data for testing and for Monday's call to demo it for a state BPS program.

**Comment by anchapin** [comment]
Alright, here's the workflow:

1. Upload the "CBL-building-performance-standards-sample-XXXX" files in SEED
2. Upload the "BPS-sample-Targets-XXXX" files in SEED
3. Upload the following files in ESPM in order listed: [Add Properties](https://docs.google.com/spreadsheets/d/13IHm3Zng3bUDuw4VUuNGtEU4_QN7jHbE/edit?usp=share_link&ouid=111561456156631389864&rtpof=true&sd=true), [Add Meters](https://docs.google.com/spreadsheets/d/14Z_rHt812NfiLZ7CZldoulfr2SpWskeL/edit?usp=share_link&ouid=111561456156631389864&rtpof=true&sd=true), and [Add Bills To Meters](https://docs.google.com/spreadsheets/d/14ap-g2XdIy4GXB5xuUnGG16EJ50_OBiz/edit?usp=share_link&ouid=111561456156631389864&rtpof=true&sd=true).
4. Within ESPM, export meter data or create reports with the data that you want (you can import the report directly into SEED with ESPM login).
5. Import data from ESPM either through spreadsheet upload or through the ESPM integration in SEED.
6. Import "BPS_Sample_AT_XXXXX" files in SEED. I think this has to be done one at a time.

**Pull request merged**
