### PR TITLE
Fixed the spinner visibility during routing transitions

### PR DESCRIPTION
**Pull request by axelstudios**
#### Any background context you want to provide?
The loading spinner that used to appear when clicking on new pages stopped showing up after upgrading the angular ui-router.

#### What's this PR do?
Restores the spinner behavior

#### How should this be manually tested?
Check that the spinner is visible during page transitions, particularly for long-running transitions like going to the inventory list view.

#1702

### CODE REVIEW

**Comment by RDmitchell** [comment]
@axelstudios -- let me know when this is on dev1 for me to test. I might also make an issue for it and put it in the test column of the Project Tracker so I will remember to test it !! Thanks !

**Comment by axelstudios** [comment]
@RDmitchell This is on dev1 now

**Comment by RDmitchell** [comment]
Thanks ! I will test !

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 5e92d8b

Fixed !! Thx !!!

**Pull request merged**
