### PR TITLE
Fix error when deleting buildings when label filter active

### PR DESCRIPTION
**Pull request by pipermerriam**
https://github.com/SEED-platform/seed/issues/712

### What was wrong?

An error in the `django-pgjson` library occurs under the condition that the `extra_data` field is queried with something like `extra_data__gt=...` and then that query is used as a subquery for another queryset.

https://github.com/djangonauts/django-pgjson/issues/35

### How was it fixed.

Force evaluation of the subquery.

#### Cute animal picture.

super-cute-kitten-pictures-awesomelycute-com-1547

### CODE REVIEW

**Comment by RDmitchell** [comment]
Looks like this PR is failing the Travis CI tests :(

**Comment by RDmitchell** [comment]
@pipermerriam @nicholasserra -- can you all figure out why this is failing the Travis CI tests so that Miles can merge it in? thx !

**Comment by nicholasserra** [comment]
Some failing python tests are deleting buildings. I may have to reopen this under a different branch to fix.

**Comment by RDmitchell** [comment]
Sure, whatever is needed. Thx !

**Comment by pipermerriam** [comment]
Huzzah! tests are green.  good to go.

**Comment by RDmitchell** [comment]
cool ! thx !!!

**Pull request merged**
