### PR TITLE
Fix filtering on "" and !"" for all data types

### PR DESCRIPTION
**Pull request by haneslinger**
#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/3759#event-8314373744

#### Screenshots (if appropriate)
image
image
image
image
image

### CODE REVIEW

**Review by nllong — CHANGES_REQUESTED** [review]
This is sooo close!  I tested this on some DC public data that had a mix of db fields, extra data, and data types.

- db number field, !"" - ✅
- db number field, "" - ✅
- db string field, !"" - ✅
- db string field, "" - ✅
- db date field, !"" - ✅
- db date field, "" - ✅
- extra number field [type string], "" - ❌
- extra number field, !"" - ❌
image 
image



More complex cases
- db field, !"" and >0 - ✅
- extra field [type number], !"" and >0 - ✅
- extra field [type number], !"" and <0 - ✅
- extra field [type number], !"" and >0.5 - ❌

image


Can we get these all in the unit tests? 

https://github.com/SEED-platform/seed/blob/Fix-filter-None-not-empty-string-on-non-strings/seed/tests/test_search.py#L17

**Comment by RDmitchell** [comment]
Seems like we need to get the 2 cases that are currently not passing the test working, ie, the extra data number fields?

**Comment by haneslinger** [comment]
yes, we are working on it now

**Comment by axelstudios** [comment]
My change fixes 3 bugs:
- `isnull` filtering related to (non-)empty strings now correctly uses booleans
- querying `extra_data` keys no longer removes all double-quotes from the data
- querying `extra_data` keys now correctly matches non-existent keys, null values, and empty strings when filtering for empty values (`=""`), and similarly can match all non-empty values

**Comment by RDmitchell** [comment]
Thanks @axelstudios !!!

**Comment by axelstudios** [comment]
Resolved more bugs:
- Fixed numeric comparisons where filter input had decimals
- Fixed empty string filtering on columns with no data type (assumes text filtering)
- Fixed `>` and `>=` bugs when deleting filters
- Fixed parsing extra_data numeric fields with comma separators in the raw values
- Fixed front-end bug that would hide all grid data in numeric columns that couldn't explicitly be parsed as a number

**Review by nllong — APPROVED** [review]
- db number field, !"" - ✅
- db number field, "" - ✅
- db string field, !"" - ✅
- db string field, "" - ✅
- db date field, !" - ✅
- db date field, "" - ✅
- extra number field [type string], "" - ✅
- extra number field, !"" - ✅

More complex cases
- db field, !"" and >0 - ✅
- extra field [type number], !"" and >0 - ✅
- extra field [type number], !"" and <0 - ✅
- extra field [type number], !"" and >10 - ✅

image

**Pull request merged**
