### PR TITLE
1298 import date field

### PR DESCRIPTION
**Pull request by nllong**
#### Any background context you want to provide?
Datetimes were not stored on when properties and taxlots were imported and/or modified. 

#### What's this PR do?
Add datetime stamps to the Property and TaxLot objects upon creation and modification. The tax lot data are stored on the Property/TaxLot tables and not the State tables. When a user updates the propertystate directly via the inventory detail page, then the database has a callback to update the Property modified time.

This PR also deprecated more API v1 around columns.

#### How should this be manually tested?
Import some data. Import another file with some modifications. Make sure that the created and updated fields change correctly in the inventory list. 

Also, try editing a detail property and taxlot and make sure that the updated datetime changes correctly.

- [x] @Myoldmopar -- in /api/v2/properties/{id}/, the id is the Property.pk, right? (not PropertyView). 

#### What are the relevant tickets?
#1298 

#### Screenshots (if appropriate)
The roll-ups look a little funny right now.
screen shot 2017-12-04 at 1 30 48 pm

#### Definition of Done:
- [x] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [x] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [x] Does this PR require a regression test? All fixes require a regression test.
- [x] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

### CODE REVIEW

**Comment by Myoldmopar** [comment]
> @Myoldmopar -- in /api/v2/properties/{id}/, the id is the Property.pk, right? (not PropertyView).

Right, `/api/v2/properties/{id}/` will lead to the [`PropertyViewSet`](https://github.com/SEED-platform/seed/blob/e3b25cae56afeadece76cc6bdbe116c966783dbf/seed/views/properties.py#L184), and on the `retrieve` function there, the `pk` is passed to the [`_get_property_view`](https://github.com/SEED-platform/seed/blob/e3b25cae56afeadece76cc6bdbe116c966783dbf/seed/views/properties.py#L408) method, which selects the `PropertyView`s that have a matching underlying `property_id` with that `pk`.

So yes.

**Comment by nllong** [comment]
thanks for double checking the `property_id`. Yeah, it would be good if you could run some manual tests. Thanks!

**Comment by Myoldmopar** [comment]
Submitted `covered_building_sample.csv`, got the following timestamps:

image

Made one change and it found the difference:

image

And now that file has an updated timestamp:

image

Manually edited the single property and also got an updated timestamp:

image

Then I took a view by tax lot:

image

And manually edited it to find a new timestamp there also:

image

This is good to go.  @nllong shall I merge?

**Comment by nllong** [comment]
merge away... just note that the roll-ups are a bit weird for now.

**Pull request merged**
