### PR TITLE
Issue #836 - Remember page number when navigating around building list.

### PR DESCRIPTION
**Pull request by nicholasserra**
#### What's this PR do?
Save page number when navigating between building list and building detail views.

#### What are the relevant tickets?
refs #836 

#### Screenshots (if appropriate)
gif

### CODE REVIEW

**Comment by RDmitchell** [comment]
@mmclark -- was this ever put onto seed production as part of our May 31 release? On seedtest, I don't see it working, even though it looks like I tested it on June 9. I am wondering if any of @nllong fixes for Sentry errors broke this ? Or maybe this didn't merged into the release 1.5 branch, which @nllong is putting his Sentry fixes against ??

anyway, it would be good if this issue could be resolved.

**Comment by nllong** [comment]
it is quite likely that my changes inadvertently broke this because the number of items per page was not persisting right in the first place. 

@tallus is there a selenium test on this that I can run locally?

**Comment by tallus** [comment]
I wrote a test  for #1005 that could be adapted

**Comment by tallus** [comment]
There's a test on branch tallus-selenium-test-836 try that.

**Pull request merged**
