### PR TITLE
Issue #13 - Delete organizations in admin panel

### PR DESCRIPTION
**Pull request by nicholasserra**
#### What's this PR do?
Adds the ability to delete entire organizations via the admin panel.

#### What are the relevant tickets?
refs #13 

#### Screenshots (if appropriate)
screen shot 2016-03-16 at 2 01 34 pm

screen shot 2016-03-16 at 2 01 42 pm

screen shot 2016-03-16 at 2 01 49 pm

#### Definition of Done:
- [x] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [x] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [x] Does this PR require a regression test? All fixes require a regression test.
- [x] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

### CODE REVIEW

**Comment by nicholasserra** [comment]
WIP as I need to add a couple tests.

**Comment by RDmitchell** [comment]
@mmclark -- is this on seedtest now? I will test if it is. thx

**Comment by nicholasserra** [comment]
FYI the data structure on this ended up being kind of complex. I think I got most cases but I won't be surprised if you find a bug :P 

via Hiptop

**Comment by mmclark** [comment]
Yes, it's there

**Comment by RDmitchell** [comment]
cool ! I'll do some testing. thx

**Pull request merged**
