### PR TITLE
Fix equivalence partitioner comparator

### PR DESCRIPTION
**Pull request by axelstudios**
#### Any background context you want to provide?
See the details in the related ticket

#### What's this PR do?
- Fixes the equivalence partitioner comparator to not compare mixed types
- Also cleans up some code in that task that was irritating me

#### How should this be manually tested?
See the details in the issue

#### What are the relevant tickets?
#2031

### CODE REVIEW

**Comment by nllong** [comment]
Looks good, just tested with the release dates. I'll merge, close, and deploy to prod tonight. Do we want to try and merge this back into develop (@axelstudios / @adrian-lara )?

**Comment by axelstudios** [comment]
I think we should merge into develop - when resolving conflicts I don't think we'll need the comparator changes any more, but the other tasks.py tweaks would be nice

**Comment by nllong** [comment]
Okay. I’ll create a PR for it now.

Da: Alex Swindler <notifications@github.com>
Risposta: SEED-platform/seed <reply@reply.github.com>
Data: venerdì dicembre 6 2019 14:48
A: SEED-platform/seed <seed@noreply.github.com>
Cc: Nicholas Long <Nicholas.Long@nrel.gov>, State change <state_change@noreply.github.com>
Oggetto: Re: [SEED-platform/seed] Fix equivalence partitioner comparator (#2032)


I think we should merge into develop - when resolving conflicts I don't think we'll need the comparator changes any more, but the other tasks.py tweaks would be nice

**Comment by adrian-lara** [comment]
Currently in `develop`, the EquivalencePartitioner is still used in automatic pairing on imports. I don't have enough context/info to know if Alex's changes are needed to avoid any potential issues there, but it could be worthwhile to bring over changes to that as well.

**Comment by RDmitchell** [comment]
I guess I will move this (PR in Test) to Done, since @nllong already closed the original issue for this.

**Comment by nllong** [comment]
I think that was the right thing to do.

**Pull request merged**
