### PR TITLE
Add delete meters UI

### PR DESCRIPTION
**Pull request by haneslinger**

### CODE REVIEW

**Review by nllong — APPROVED** [review]
Looks great! I say we get this into the release and then handle the "editing" and "creating" next.

image

**Review by nllong — CHANGES_REQUESTED** [review]
Hmm, it looks like the "monthly" and "yearly" aggregations aren't working anymore. Can you take a look at what might be causing it?

**Comment by haneslinger** [comment]
good catch! fixed. I don't know if I like `refresh_meters_and_readings` and `refresh_readings` as two different functions. I will rethink this

**Comment by nllong** [comment]
> good catch! fixed. I don't know if I like `refresh_meters_and_readings` and `refresh_readings` as two different functions. I will rethink this

Great thanks! Yeah, this page could use a little love. Probably good to create patterns that we can use on sensors too.

**Comment by RDmitchell** [comment]
Instance: staging
SHA: bb2fdd425
Org: LBNL Test 200
Cycle: Meter Import Testing

The UI for deleting the meters exists. 
image

And it deletes the meter data, in this case the solar data
image

**Pull request merged**
