### PR TITLE
Update bricr-prod to bricr-dev

### PR DESCRIPTION
**Pull request by macintoshpie**

### CODE REVIEW

**Comment by nllong** [comment]
@macintoshpie I resolved the conflicts. I'll check to make sure that the tests passed tomorrow and will merge if all is good.

**Comment by nllong** [comment]
@macintoshpie -- nvm.. I think this is ready to merge, any reason not to?

**Comment by macintoshpie** [comment]
@nllong I think we're good to go, let's merge it

**Comment by nllong** [comment]
@macintoshpie --done. enjoy!

**Pull request merged**
