### PR TITLE
Fix: Use old cycles during unmerge

### PR DESCRIPTION
**Pull request by haneslinger**
In contrast to https://github.com/SEED-platform/seed/issues/3904, here's the new workflow

Okay, so we've got a property present in two cycles, one has been merged into:
image
image

see?
image

Now if we unmerge the merged one:
image

We've one got one new property:
image

### CODE REVIEW

**Comment by haneslinger** [comment]
@kflemin @axelstudios the failing test here imply this intented behavoir. why? Is it still?

**Comment by kflemin** [comment]
I don't have any historical context for this one. @nllong? @axelstudios?   Basically, what we are trying to do here is: when we unmerge 2 properties, we want to associate one of the unmerged properties back to the "old" existing property and create a new property for the other unmerged property.  This is in contrast to what happens now:  when a property is "unmerged" into 2, it creates 2 new properties.

**Comment by haneslinger** [comment]
@kflemin @axelstudios repinging this

**Comment by kflemin** [comment]
**Resolution:**
- assign meters to both properties
- 1 of the unmerged properties should retain the history
- in the notes of the property that has no history, add a note "unmerged from X" so we still retain a link to the history (db table note)

**Comment by haneslinger** [comment]
@kflemin In the note, what field should I use the reference the other Property?

**Comment by kflemin** [comment]
> @kflemin In the note, what field should I use the reference the other Property?

Let's reference the property view ID (since users don't have access to property IDs directly).

**Review by kflemin — APPROVED** [review]

**Pull request merged**
