### PR TITLE
#456 celery classification fix

### PR DESCRIPTION
**Pull request by rHorsey**
Fixes issue #456 and also potentially issue #239, although this needs to be further verified.

### CODE REVIEW

**Comment by rebrownlbnl** [comment]
Do the Travis results include the test_firefox test?

**Comment by rHorsey** [comment]
Yep. When I renamed the test on the prior pull request the test ended up untracked, but if you look at the files changed you'll see that the test_firefox script is re-included.

**Comment by mmclark** [comment]
Ry - this branch has conflicts with develop.  Can you resolve and re-submit, please?

**Comment by rHorsey** [comment]
https://github.com/SEED-platform/seed/blob/develop/seed/cleansing/views.py#L22 was updated but not with the new cache code. Fixed the line and all tests are still good.

**Comment by mmclark** [comment]
Thanks!

**Comment by rHorsey** [comment]
Does everything look good for merging?

**Comment by rebrownlbnl** [comment]
+1

**Pull request merged**
