### PR TITLE
432 pass primary keys

### PR DESCRIPTION
**Pull request by nllong**
This fixes celery to use JSON persistence again (instead of pickling). 

This PR also has fixes for various formatting errors that were breaking travis.

### CODE REVIEW

**Comment by nllong** [comment]
fixes #432

**Comment by RDmitchell** [comment]
@nllong -- is there any UI testing that I can do to confirm that this is working? Or do we just rely on the CI testing passing and close this issue?

**Comment by nllong** [comment]
The same testing on the backend will cover this PR.

**Comment by rebrownlbnl** [comment]
:+1:

**Comment by nicholasserra** [comment]
So I may be running into some issues with this. Seems that the variable `tasks` includes dicts with datetime objects at this point:

https://github.com/SEED-platform/seed/blob/develop/seed/tasks.py#L872

Leading to json serialization errors when importing excel spreadsheets with dates. Trying to figure out a workaround right now, but wanted to give a heads up in case you have any fixes in mind.

**Comment by nicholasserra** [comment]
Also seems that `finish_raw_save` doesn't even need the `results` key, so i'm looking at removing it. I'm a little fuzzy on the celery subtask stuff. 

cc @RDmitchell @rebrownlbnl to test this fix with excel spreadsheets with dates

**Comment by nicholasserra** [comment]
Confirmed that reverting this fixes datetime import issues.I'm going to finish my other ticket then hop on this.

**Comment by RDmitchell** [comment]
thx Nick !

**Comment by nllong** [comment]
Ugh. I must have missed this. I can help if you need it. 

- nick

**Comment by nicholasserra** [comment]
We might be able to write a json serializer to accept datetime objects. That's what i'm looking at.

**Pull request merged**
