### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nllong**
#### Any background context you want to provide?
The dependencies around tests were out of date and the requests package was flagged as a security threat.

#### What's this PR do?
Updates the old dependencies to the most recent version. This also fixes several of the tests so that Travis should now pass.

#### How should this be manually tested?
N/A

#### Screenshots (if appropriate)
N/A
#### Definition of Done:

- [X] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [X] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [X] Does this PR require a regression test? All fixes require a regression test.
- [X] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated? **YES**

### CODE REVIEW

**Comment by rebrownlbnl** [comment]
Looks like Travis is still failing.

**Comment by nllong** [comment]
you had to rain on my parade, didn't you?! 😄

**Comment by rebrownlbnl** [comment]
Sorry!

**Comment by nllong** [comment]
it was strange because the push passed, but the PR didn't. let's try this again.

**Comment by nllong** [comment]
better @rebrownlbnl 😆

**Pull request merged**
