### PR TITLE
Bluesky UI-Grid

### PR DESCRIPTION
**Pull request by axelstudios**
Updated the bluesky tabs to use the new UI-Grid

### CODE REVIEW

**Comment by RDmitchell** [comment]
Great ! Can't wait to see this !

**Comment by mmclark** [comment]
I merged the PR, pulled changes on seeddev, installed java dependencies (for angular-ui-grid), ran gulp sass and restarted everything.  Looks like there are some problems:

nimbus-image-1466656168888

@axelstudios Did I miss anything in the deploy?

**Comment by axelstudios** [comment]
@mmclark My first guess is that you need to run `./manage.py migrate`.  I think you may be missing https://github.com/SEED-platform/seed/blob/bluesky/seed/migrations/0018_auto_20160614_1330.py

**Comment by mmclark** [comment]
@axelstudios That was it, thanks.  I didn't see migrations in the PR, so didn't run them.

**Comment by RDmitchell** [comment]
Just did a quick test, looks good ! thanks

**Pull request merged**
