### PR TITLE
Add Import Export to Audit Template

### PR DESCRIPTION
**Pull request by perryr16**
### Any background context you want to provide?
SEED currently has functionality to update an individual property with [Audit Template](https://buildingenergyscore.energy.gov/rp/buildings) building data. The function leverages the Audit Template API endpoint [GET /api/v2/building_sync/download/rp/buildings/:id](https://api.labworks.org/apidoc/v2/building_sync/download.html). The returned XML is used to create a new PropertyState and associate it with the current PropertyView.

#### Import Features
--------
Adds the ability to batch update properties with data from audit template.

From the Data page, a user may now import Audit Template Buildings via the Add Data Files button. A request is sent to the linked Audit Template account to get all buildings associated with the account details at [GET /api/v2/rp/buildings](https://api.labworks.org/apidoc/v2/buildings/index.html). Backend logic determines which audit tempatae buildings match existing properties for the selected cycle. Matching is solely based on the PropertyState field `audit_template_building_id`. The results are displayed to the user where they may sort/filter results and select which properties to continue to update. Selected properties are looped through and XML files are fetched from the Audit Template API endpoint `GET /api/v2/building_sync/download/rp/buildings/:id`. PropertyViews are updated with the corresponding XMLs.

All Audit Template requests are made within the `seed_celery` container. 

The current implementation can lead to very long wait times. For example, a request to get a building xml for a single building takes ~ 5 seconds. Updating 1000 properties would take about an hour and a half to complete.

The only property that exists in both the PropertyState and the Audit Template Tool is `audit_template_building_id` (`id` on Audit Template). This requires SEED properties to be updated with correct `audit_tempalte_building_id`s which can be time consuming.

If the matching criteria were to change, the audit template get_buildings response must be updated to include properties like `pm_property_id`, `ubid`, or `custom_id`. Below is the current response structure.

```
GET /api/v2/rp/buildings
[{
    "id": 369,
    "name": "New Buildng",
    "owner": {
        "id": 877,  "email": "[test](mailto:test@nrel.gov)", "first_name": "test",
        "last_name": "test",  "organization": { "id": 9, 
        "name": "National Renewable Energy Laboratory - SEED Project" }, 
        "site_admin": false,  "type": "User" 
     },
    "report": {
      "id": 2, "name": "New York City Energy Efficiency Report",
      "city": { "id": 2, "name": "New York", "state": "NY" }
    },
   "status": "Editing",
   "submissions": [],
   "created_at": "2018-08-22T12:21:43.519-07:00",
   "updated_at": "2023-04-04T12:31:04.100-07:00",
   "html_url": "<html_url>",
   "submission_history_html_url": "<history_url>",
   "xml_url":  "<xml_url>"
  },
   ….
]
```
#### Export Features
-------
From the inventory list a selection of properties can be exported to the linked Audit Template account. Properties that already have an Audit Template Building ID will be skipped as Audit Template does not have an update feature and will result in duplicates. For valid properties, an XML file will be created for each. Because of Audit Template import requirements, XML's will be limited to the following fields: address_line_1, city, gross_floor_area, postal_code, property_name, state, year_built, and report type (set as an organization setting). Properties that do not meet the requirements will be skipped. 

The Organization settings have a new "Audit Template" tab where a user can select the organization-wide report type from an accepted list of valid report types.

This process is initiated from the inventory list actions. A new Export to AT modal directs users through the export process showing a confirmation, a status bar, and results.

#### Next Steps
Currently, the export process only applies the hardcoded to the fields listed above. Investigate what it would take to have a more dynamic property to xml process. This would be loosely the inverse of the /building_sync/mappings.py `BASE_MAPPING_V2`

### Known issues
- In the import modal, filtering the Audit template buildings only supports exact matches at the moment, not '<10', '>20'

- The report type "New York City Energy Efficiency Report" fails to export to Audit Template and it has been removed from the selectable report types.

#### 1. Export a stub to Audit Template
Inventory List > Select a number of properties > Actions > Export to Audit Template and go through the prompts
Test with 3 different property scenarios 
- Valid properties: properties that have address_line_1, city, gross_floor_area, postal_code, property_name, state, year_built and no audit_template_building_id 
- Existing properties: properties that have already been uploaded to AT or imported from AT. These are any property that already has an audit_template_building_id 
- Invalid properties: properties that are missing any of the above fields.
#### 2. Update values on Audit Template 
Log into your audit template account and make a change to the property, ex: change gross floor area
#### 3. Import audit template data
Data > Add Data Files > Import Audit Template Buildings > Confirm > select properties > Update
The inventory should reflect the changes made on Audit Template

### What are the relevant tickets?
#3770 

#### Export
Screenshot 2023-09-07 at 4 18 22 PM
Screenshot 2023-09-07 at 4 18 30 PM
Screenshot 2023-09-07 at 4 19 09 PM

Screenshot 2023-09-08 at 11 39 04 AM
Screenshot 2023-09-08 at 11 39 09 AM

#### Import
Screenshot 2023-07-26 at 9 41 18 AM
Screenshot 2023-07-26 at 9 41 23 AM
Screenshot 2023-07-26 at 9 41 34 AM

Screenshot 2023-07-26 at 9 43 03 AM
Screenshot 2023-07-26 at 9 43 13 AM
Screenshot 2023-07-26 at 9 43 24 AM

### CODE REVIEW

**Review by kflemin — APPROVED** [review]
apart from the minor tweaks we discussed, this is great!🏆

**Comment by perryr16** [comment]
Updates based on feedback from @kflemin:
- Imported AT XMLs were overwriting the SEED column "Property Name" with a "Building ID". The mapping has been removed and existing Property Names will not be overwritten. 
- Added inventory detail action "Export to Audit Template"
- The "Only show populated columns" action failed to show "Audit Template Updated". The action uses property state history to determine which columns to show. "Audit Template Updated" needed to be appended to the `PropertyState` associated with the xml `BuildingFile`
- Export modal results table styling
Screenshot 2023-09-15 at 2 33 49 PM

**Review by kflemin — APPROVED** [review]
🏆

**Comment by kflemin** [comment]
@perryr16, can you get this PR updated w/ develop. once that's done I think it's ready for @axelstudios's final review and merge!

**Review by axelstudios — APPROVED** [review]

**Pull request merged**
