### PR TITLE
BETTER v1.7 updates

### PR DESCRIPTION
**Pull request by kflemin**
Updates to support BETTER version 1.7

BETTER anticipated release schedule:
  - currently on BETTER dev server
  - on staging 6/15
  - on prod 6/30

Updates:
1. updated ee_measures, both the list and the structure to use TOKEN rather than name
2. updated path to results in results array (a element named 'assessment_results' was introduced in the 'assessment' hash)
3. added support for Public Library and Restaurant

To test, ensure that you are pointed to the BETTER DEV server (https://better-lbnl-development.herokuapp.com/).  Run analyses and ensure they run successfully and you can get results.

#4671, #4678

DO NOT MERGE until BETTER v1.7 is deployed on the BETTER production server.

### CODE REVIEW

**Comment by RDmitchell** [comment]
It looks like seed dev1 is pointing to the BETTER production server right now - might want to change that to the BETTER dev server? 

image

**Comment by RDmitchell** [comment]
Looks like seeddemostaging is set to the BETTER staging server.
image

**Comment by RDmitchell** [comment]
@kflemin -- so it seems like the 2 dev servers need to be set to point to the BETTER develop server. Thanks !!

**Comment by kflemin** [comment]
@RDmitchell, yep, we'll have to make that change when we deploy these updates for sure!  this one will be a bit tricky to coordinate testing on the server since the changes are not compatible with the earlier versions of BETTER, but we will make it work!

**Comment by RDmitchell** [comment]
@kflemin -- thanks and have a good 3 day weekend !! Time to stop working !!

**Review by axelstudios — APPROVED** [review]

**Pull request merged**
