### PR TITLE
Issue #894 - Django 1.9 upgrade

### PR DESCRIPTION
**Pull request by nicholasserra**
#### Any background context you want to provide?
We need Django 1.9 to fix some migrations.

#### What's this PR do?
Bump to Django 1.9

#### How should this be manually tested?
All main stuff needs tested.

#### What are the relevant tickets?
Refs #894 

#### Definition of Done:
- [x] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [x] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [x] Does this PR require a regression test? All fixes require a regression test.
- [x] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

### CODE REVIEW

**Comment by nicholasserra** [comment]
@nllong Hoping you can help me figure out why the spelling step seems totally broken on this. Thanks!

**Comment by nllong** [comment]
Looking at travis, it just looks like the word Accessor/accessor is not a valid word for some reason. I added it to the [spelling list](https://github.com/SEED-platform/seed/blob/django-19/docs/source/spelling_wordlist.txt).

screen shot 2016-04-06 at 10 46 44 am

**Comment by rebrownlbnl** [comment]
looks like tests are still failing

**Comment by nicholasserra** [comment]
Yeah there's some kind of merge test failing. Needs a bit more work, but looks like we're 99% there.

**Comment by nicholasserra** [comment]
And now we're green. Just needed to clear travis build cache.

**Comment by mmclark** [comment]
Given there were some issues with migrations, is there anything to be aware of when upgrading?  I assume the standard pull, pip install, migrate, collectstatic dance will do the trick, but if there are any potholes, let me know!

**Comment by nicholasserra** [comment]
@mmclark let me double check migration stuff. I'll migrate this on a clean copy of the seedtest db dump you gave me last week. This PR doesn't add or change any migrations, so should be fine, but i'll check again.

**Comment by mmclark** [comment]
Thanks!

**Comment by nicholasserra** [comment]
Added one more change to a package. Migrated against the seedtest db dump, everything looks good :)

**Comment by mmclark** [comment]
@nicholasserra It looks like travis is failing - a missing tox.ini file.  Is this an issue?  Possible to resolve?

**Comment by nicholasserra** [comment]
Job just needed restarted.

**Comment by mmclark** [comment]
Great - thanks.

**Comment by mmclark** [comment]
Loaded on seedtest

**Pull request merged**
