### PR TITLE
3295 column desc field memo box

### PR DESCRIPTION
**Pull request by anchapin**
#### Any background context you want to provide?
The column description field in the column settings page was too narrow.

#### What's this PR do?
Set minimum width to 350 pixels.

#### How should this be manually tested?
Go to column settings page in an organization and check that the column description field is wide enough.

#### What are the relevant tickets?
#3295

### CODE REVIEW

**Comment by RDmitchell** [comment]
@anchapin -- this looks good to me.

**Review by nllong — APPROVED** [review]
looks good!

image

**Comment by nllong** [comment]
Actually, it looks like the updates to the Excel files may have caused some corruption? Any one else seeing this?

image

**Review by nllong — CHANGES_REQUESTED** [review]
It looks like you just changed the permissions of the Excel files, which should be okay, but can you confirm you can open them with Mac Excel?

**Comment by anchapin** [comment]
> It looks like you just changed the permissions of the Excel files, which should be okay, but can you confirm you can open them with Mac Excel?

This has been fixed. Should I go ahead and merge this pull request?

**Review by nllong — APPROVED** [review]
sweet, the test files work now!

**Pull request merged**
