### PR TITLE
This adds setup instructions for Docker on Ubuntu

### PR DESCRIPTION
**Pull request by tallus**
#### Any background context you want to provide?
The setup instructions for Docker where Windows/OS X centric and did not work
for Ubuntu. This pull request was based on what I did to get it working. 

#### What's this PR do?
This adds setup instructions for Docker on Ubuntu

- setting up Docker
- optional instructions for Virtual Box
- alternative option to run  Docker locally, with the local repo used  as a volume for the web server so local changes are reflected there.

#### How should this be manually tested?
Pull the repo to a clean directory (ideally on a fresh install) on an Ubuntu box and follow
the instructions.
#### What are the relevant tickets?
None. This is based on the work I did setting up my dev environment.
#### Definition of Done:
This contains changes to documentation only.  It should be checked for clarity and validated
(this is based on the  process I followed, but naturally that took some experimentation so its not an exact match) If needed extra tickets should be created so the process can be improved and the 
work-arounds eliminated.

### CODE REVIEW

**Comment by rebrownlbnl** [comment]
Tests are failing, otherwise looks good to me.
@nllong - any comments?

**Comment by tallus** [comment]
I've attached the errors I get from make spelling
It looks like there might be some missing dependencies, though that might be my local setup. I had to reinstall a couple of modules  to get make spelling to work as installing from the requirements files didn't seem to have pulled in all the dependencies? 

[sphinx.errors.txt](https://github.com/SEED-platform/seed/files/284950/sphinx.errors.txt)

**Comment by nllong** [comment]
Thanks for updating the instructions. The errors are these words:

setup_docker.rst:110:similiar:
setup_docker.rst:139:rmi:
setup_docker.rst:168:ip:
setup_docker.rst:174:sytem:
setup_docker.rst:203:virtualenvs:
setup_docker.rst:203:virtualenvs:
setup_docker.rst:203:wil:
setup_docker.rst:216:redis:
setup_docker.rst:222:commmits:
setup_docker.rst:229:afterwards:
setup_docker.rst:256:ip:
setup_docker.rst:256:lsited:
setup_docker.rst:276:Ctrl:
setup_docker.rst:278:collectstatic:

If they are real words (e..g virtualenvs), then add them to https://github.com/SEED-platform/seed/blob/develop/docs/source/spelling_wordlist.txt

**Comment by tallus** [comment]
Fixed up the spelling and everything is passing.

**Comment by rebrownlbnl** [comment]
hey, the spellchecker works!

**Pull request merged**
