### PR TITLE
refactor: include Electricity - Unknown meter type in analyses

### PR DESCRIPTION
**Pull request by macintoshpie**
#### Any background context you want to provide?
See issue

#### What's this PR do?
- includes meter types "Electricity - Unknown" in all of SEED's analyses

#### How should this be manually tested?
- Import this type of meter for a property (e.g. custom data report from ESPM), then run an analysis on that property

#### What are the relevant tickets?
#3014

### CODE REVIEW

**Comment by macintoshpie** [comment]
@nllong I wasn't able to successfully run the BETTER analysis (I only have demo API token and that server is in maintenance mode right now...). But I did check the BSync files it built and it included all 12 readings when importing the custom data report provided in #3013 

If you have a production API token, could you test this?

**Review by nllong — APPROVED** [review]
lots of savings! Looks great!
image

**Comment by nllong** [comment]
@macintoshpie - can you merge after confirming that EUI and CO2 calcs work with unknown?

**Comment by macintoshpie** [comment]
After updating our other analyses, I was able to run them on the Electricity - Unknown meter data. Note that you MUST manually edit the eGRID Subregion Code column for a property to run the CO2 analysis (unless you edit your spreadsheet and map to it)
Screen Shot 2021-11-19 at 11 44 02 AM
Screen Shot 2021-11-19 at 11 39 11 AM

**Pull request merged**
