### PR TITLE
Issue #943 - Fixes for api test

### PR DESCRIPTION
**Pull request by nicholasserra**
#### What's this PR do?
Fixes for the api test script. Reworked how the whole thing is set up. It now runs with the travis build. Now has option to runserver along with the test (for travis). Now has option for no input.

#### What are the relevant tickets?
Refs #943 

#### Screenshots (if appropriate)
screen shot 2016-05-16 at 3 18 02 pm

#### Definition of Done:
- [x] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [x] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [x] Does this PR require a regression test? All fixes require a regression test.
- [x] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

### CODE REVIEW

**Comment by RDmitchell** [comment]
@nicholasserra -- also the tests are failing on this PR.

**Comment by nicholasserra** [comment]
Can't figure out this failure. Hoping when everything else is merged this one will be fixed.

**Comment by rebrownlbnl** [comment]
I notice the API test fixture includes a hash of the bravache user password.
Is that a security issue having that in the repo?
Or is that user created from scratch every time a test is run, so the password can be anything?

**Comment by nicholasserra** [comment]
That hash is only used for testing, it's not a valid password anywhere except the test database while it's running.

**Comment by rebrownlbnl** [comment]
thanks, that's what I suspected, so it's fine.

**Comment by mmclark** [comment]
Loaded on seedtest

**Pull request merged**
