### PR TITLE
Piper/issue 440 add or update license to all files

### PR DESCRIPTION
**Pull request by pipermerriam**
https://github.com/SEED-platform/seed/issues/440

### What was wrong?

The licensing information at the top of each python file was not consistent in presence or format, as well as many of the copyright dates being 2014.

### How was it fixed.

* [x] Updated all python files in the repository to have the updated license 
* [x] update js files
* [x] update html files

#### Cute animal picture

5 16 15-cutest-sleeping-puppies5

### CODE REVIEW

**Comment by pipermerriam** [comment]
Good to merge when tests pass.

**Comment by RDmitchell** [comment]
thanks Piper!

**Comment by rebrownlbnl** [comment]
:+1:

**Comment by RDmitchell** [comment]
Thanks Miles !

**Pull request merged**
