### PR TITLE
Dockerized Seed Platform

### PR DESCRIPTION
**Pull request by teeterc**
This import dockerizes the seed platform.  And updated README.md is included.

### CODE REVIEW

**Comment by StephenCzarnecki** [comment]
Thanks, I will create a clean ubuntu machine and follow the readme to test.

**Comment by StephenCzarnecki** [comment]
Hi

When I try to follow the readme I get to the line
docker exec -ti seed-postgres createdb -U postgres seed
But that gives me
Error: Command not found: exec
Error: Command not found: -ti

I'm still a bit new to dockers but looking at their docs they clearly mention the exec command
https://docs.docker.com/reference/commandline/cli/#exec

And, unless I missed it, there does not appear to be anything special that needs to be installed to enable the exec command.  I started with a completely clean Ubuntu 14.04 vm so if you have any suggestions I would appreciate them.

Thanks.

**Comment by dangunter** [comment]
You probably have an older version of docker. Do docker --version and look
at the docs for that version.

# [Dan Gunter](http://acs.lbl.gov/~dang)

**Comment by StephenCzarnecki** [comment]
Dan - Thanks.  I patched to the latest version of Docker via https://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation and now am able to follow the readme to the end and can browse to the webpage on localhost and log into the web page.

**Comment by rebrownlbnl** [comment]
Please run the API tests against SEED running in docker, to ensure the application is working properly. API tests are here: https://github.com/SEED-platform/seed/blob/master/seed/tests/test_seed_host_api.py

**Comment by StephenCzarnecki** [comment]
I tried to run the tests and got to the point where 5 or so passed but then they failed.  Talked to Claudine and she said that I probably needed to get the latest code out of seed to make the tests pass.  After getting the latest code now I can't get the uwsgi docker to start.  I tried removing all containers and images and building them again but that did not help.

Below is the command I am using to try and run the container (copy/pasted from the readme) as well as the results from docker images, docker ps -a, and the docker log from the container.

ubuntu@ubuntu:~/seed$ sudo docker run -d -name seed-uwsgi -v $HOME/seed_data:/seed/collected_static --link seed-redis:redis --link seed-postgres:postgres -p 8000:8000 seed-platform /seed/bin/start_uwsgi_docker.sh
Warning: '-name' is deprecated, it will be replaced by '--name' soon. See usage.
6b0a625d5fb0a045e0788503e470ac139458ef3a3a027f792066cfa76db842e3

ubuntu@ubuntu:~/seed$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
seed-platform       latest              90ccb1700101        15 minutes ago      1.556 GB
postgres            latest              6dc733527d22        26 hours ago        213.9 MB
ubuntu              14.04               5ba9dab47459        3 weeks ago         188.3 MB
ubuntu              14.04.1             5ba9dab47459        3 weeks ago         188.3 MB
ubuntu              latest              5ba9dab47459        3 weeks ago         188.3 MB
ubuntu              trusty              5ba9dab47459        3 weeks ago         188.3 MB
redis               latest              868be653dea3        3 weeks ago         110.8 MB

ubuntu@ubuntu:~/seed$ sudo docker ps -a
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS                     PORTS               NAMES
6b0a625d5fb0        seed-platform:latest   "/seed/bin/start_uws   8 seconds ago       Exited (1) 7 seconds ago                       seed-uwsgi           
8cd15f5c3e75        seed-platform:latest   "/seed/bin/setup_dat   2 minutes ago       Exited (0) 2 minutes ago                       hungry_ardinghelli   
a097bbe0e483        postgres:latest        "/docker-entrypoint.   3 minutes ago       Up 3 minutes               5432/tcp            seed-postgres        
d3963554e264        redis:latest           "/entrypoint.sh redi   3 minutes ago       Up 3 minutes               6379/tcp            seed-redis           

ubuntu@ubuntu:~/seed$ sudo docker logs 6b0a625d5fb0
Traceback (most recent call last):
  File "/usr/local/bin/newrelic-admin", line 9, in <module>
    load_entry_point('newrelic==2.20.0.17', 'console_scripts', 'newrelic-admin')()
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.20.0.17/newrelic/admin/__init__.py", line 128, in main
    callback(sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.20.0.17/newrelic/admin/run_program.py", line 96, in run_program
    os.execl(program_exe_path, *args)
  File "/usr/lib/python2.7/os.py", line 312, in execl
    execv(file, args)
OSError: [Errno 2] No such file or directory

**Comment by StephenCzarnecki** [comment]
Removed all the code and all the docker images, rebuilt everything and it works.  Whatever was wrong, mea culpa.  Ran API tests (output follows) and they pass until they get to 

API Function: export_buildings_download ...not passed

Talked briefly with Claudine and she showed me how to do the failing test manually which also hangs.  Will ask in the next meeting if anyone else has experienced anything similar.

ubuntu@ubuntu:~/seed/seed/tests/api$ sudo python test_seed_host_api.py 

-------Accounts-------

API Function: get_user_profile ...passed
API Function: get_organizations ...passed
API Function: get_organization ...passed
API Function: update_user ...passed
API Function: get_organizations_users ...passed
API Function: get_query_threshold ...passed
API Function: get_shared_fields ...passed

-------Dataset-------

API Function: create_dataset ...passed

|---Covered Building File---|

API Function: upload_file ...passed
API Function: save_raw_data ...passed
API Function: save_column_mappings ...passed
API Function: remap_buildings ...passed
API Function: get_column_mapping_suggestions ...passed
API Function: start_system_matching ...passed

|---Portfolio Manager File---|

API Function: upload_file ...passed
API Function: save_raw_data ...passed
API Function: save_column_mappings ...passed
API Function: remap_buildings ...passed
API Function: get_column_mapping_suggestions ...passed
API Function: start_system_matching ...passed

API Function: get_PM_filter_by_counts ...passed
API Function: search_buildings ...passed

-------Project-------

API Function: create_project ...passed
API Function: get_project ...passed
API Function: add_buildings_to_project ...passed

-------Labels-------

API Function: add_label (test label)  ...passed
API Function: get_labels ...passed
API Function: apply_label ...passed

-------Export-------

API Function: export_buildings ...passed
API Function: export_buildings_download ...not passed
Traceback (most recent call last):
  File "test_seed_host_api.py", line 671, in <module>
    checkStatus(result, fileout)  
  File "test_seed_host_api.py", line 182, in checkStatus
    raise RuntimeError(msg)
RuntimeError: INTERNAL SERVER ERROR

**Comment by rebrownlbnl** [comment]
Looks ready to merge.
That last export error is not related to the Docker code.

**Comment by danielmcquillen** [comment]
Hi,

On OSX building the Dockerfile fails towards the end with the error:
```
     Fatal error: Unable to find local grunt.
```
I'm relatively new to Docker and to Grunt so sorry if this is a silly question: shouldn't there be a package.json file with the grunt dependency defined? That way grunt and dependencies would be installed when npm install is called. 

Since this isn't failing for others there must be something wrong on my setup. Thanks for your thoughts.

**Pull request merged**
