### PR TITLE
3240 feat/save ghg results

### PR DESCRIPTION
**Pull request by Ryoken**
#### Any background context you want to provide?
See ticket.

#### What's this PR do?
Saves CO2 analysiis results to the PropertyState.

#### How should this be manually tested?
Run an anlysis and check the property's values.

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/3175

#### Screenshots (if appropriate)
Analysis:
Screen Shot 2022-05-11 at 4 05 59 PM
PropertyState:
Screen Shot 2022-05-11 at 4 05 40 PM

### CODE REVIEW

**Comment by perryr16** [comment]
A couple questions based on Nicks comments in the issue 
> I think we need to update the CO2 analysis to report as actual fields now. Here is what I propose:
> 1. Add in an CO2 analysis setting to ask if the results should override the default property columns
> 2. Average Annual CO2 (kgCO2e) -> MtCO2e (so just divide by 1000)
> 3. Total Marginal GHG -> Total Marginal GHG Emissions (MtCO2e/year) [added in #3174]
> 4. Total GHG Emissions Intensity (kgCO2e/ft2/year and kgCO2e/m2/year) -> Average Annual CO2 divided by gross floor area in kgCO2/ft2/year
> 5. Total Marginal GHG Emissions Intensity -> Total Marginal GHG Emissions Intensity (kgCO2e/ft2/year and kgCO2e/m2/year) [added in #3174]

1. I didn't get a prompt to ask if the results should override 
2. Functional
3. Showing Blank
4. Functional
5. Showing Blank

Let me know if I'm misunderstanding the ticket, otherwise looks good!
Screen Shot 2022-05-13 at 1 17 43 PM

**Comment by Ryoken** [comment]
> * Add in an CO2 analysis setting to ask if the results should override the default property columns

Ah, I missed this setting, thanks!  Regarding the rest: I had spoken with Nick in person and confirmed that we don't actually get those missing values.  We are just concerned with saving the values we are getting, and currently that's just nothing "marginal".  Long story short this is due to the type and quality of meter data we get.

**Comment by perryr16** [comment]
Ok Great. Pending that setting full approval

**Review by nllong — APPROVED** [review]
nice! I see metric tons and kg/ft2... looks right.

**Pull request merged**
