### PR TITLE
Issue 20 - JSON field exact and null searches

### PR DESCRIPTION
**Pull request by nicholasserra**
Enable exact and "null" searches on the Building extra_data json blob.

This fix needed a less than ideal hack for the "null" filtering. When fields are mapped and added to the building json blob, they are only added if they contain data. So i'm doing a `contains` query on the JSONField to see if it contains what looks like a key for that field. 

When we bump to Django 1.7, we can update the postgres JsonField package, and make use of postgres's "has" filter. This note was added as a comment in the code.

Refs #20

### CODE REVIEW

**Comment by RDmitchell** [comment]
Yes it’s a problem in the JSON field that if there is no data in the original imported data, the field is not there. It is on the list to deal with, ie, maybe we need to force the fields without data to still be written into the JSON blob field with “null” data.

**Comment by nicholasserra** [comment]
Yeah that's an option. I wanted this to be backwards compatible until we upgrade package versions. 

via Hiptop

**Comment by RDmitchell** [comment]
Right. We won’t implement that fix now.

**Comment by RDmitchell** [comment]
This PR has been tested on seedtest and is working

**Pull request merged**
