### PR TITLE
Issue #858 - Spinner during label save

### PR DESCRIPTION
**Pull request by nicholasserra**
#### What's this PR do?
Adds a spinner while adding labels to buildings.

#### What are the relevant tickets?
Refs #858 

#### Definition of Done:
- [x] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [x] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [x] Does this PR require a regression test? All fixes require a regression test.
- [x] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

### CODE REVIEW

**Comment by mmclark** [comment]
@nicholasserra There are some conflicts in this branch after merging other PRs.  Can you take a look?

**Comment by nicholasserra** [comment]
Fixed

**Comment by RDmitchell** [comment]
any reason this can't be labeled as ready?

**Comment by nicholasserra** [comment]
Ready

**Comment by mmclark** [comment]
Loaded on seedtest

**Pull request merged**
