### PR TITLE
fix: only collect columns that aren't related

### PR DESCRIPTION
**Pull request by Ryoken**
#### Any background context you want to provide?
When the backend attempted to filter on a column that had a non-unique name, it would pull the most recent column instead of the appropriatee column.  This came up when "related data" was causing the same column name to be present twice.

#### What's this PR do?
Excludes the columns with "related data" when building the list of column s by table name so the correct column should always be present.

#### How should this be manually tested?
Ensure filtering works on a field that isn't related but has a related column by the same name (such as "Address Line 1").

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/3499

### CODE REVIEW

**Comment by anchapin** [comment]
I'm still getting the same issue. See screenshot below for an example using "Address Line 1" column.
image

**Comment by Ryoken** [comment]
> I'm still getting the same issue. See screenshot below for an example using "Address Line 1" column. image

uhhh, what on earth happened to my commit?  the changes I made were gone, and the commit is now showing that I changed half the file that I didn't even touch.

I'm going to re-push my change and see if that resolves it.

**Review by anchapin — APPROVED** [review]
It works for me now. Thank you for this fix.

**Review by haneslinger — APPROVED** [review]
Nice work!

**Pull request merged**
