### PR TITLE
feat(models): add stats to analysis.pys

### PR DESCRIPTION
**Pull request by laurenliz22**
#### Any background context you want to provide?
Added code to develop analysis statistics around the inventory properties

#### What's this PR do?
API to create JSON output of analysis statistics around the inventory properties

#### How should this be manually tested?
run the API in Firefox filling in the organizaton_id and cycle_id: example = http://0.0.0.0:8000/api/v3/analyses/stats/?organization_id=1&cycle_id=2

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/2660

### CODE REVIEW

**Review by macintoshpie — COMMENTED** [review]
This is looking good! A few thoughts about what we could tweak / improve:
1. Having user-friendly chart and axis titles would be nice
2. having user friendly text in the table would be nice
3. I think we could improve the appearance of the table a bit. Maybe we could make it look more like the inventory list table with a little CSS?
Screen Shot 2021-07-26 at 12 24 57 PM

**Comment by macintoshpie** [comment]
One more thought, if a chart will be empty then we should hide it from display

**Comment by laurenliz22** [comment]
@macintoshpie This has been pushed up with the changes above.  Please reach out if you have any additional changes/questions.  Thanks!

**Review by macintoshpie — APPROVED** [review]
Awesome! This looks great ✨ 

I tweaked the charts so that if they're missing data it'll say so on the chart with some text
Screen Shot 2021-08-09 at 2 16 08 PM

I also tweaked the stats endpoint to standardize unit-aware fields just in case a user has imported data with different units.

I think this is ready to be merged! There is some followup work we will do to "finish" this page:
- summarize how many properties have non-null values for columns of interest (we have 
- ??? I think there might have been another but I can't remember currently

**Pull request merged**
