### PR TITLE
Allow the mapping columns to be resizable

### LINKED ISSUE #1337: SEED Header input box in Mapping -- need to be able to make column wide enough to see long field names
V 2.0.2

When importing a Portfolio Manager file, there are many fields that are very long. 
Right now in SEED, it is not possible to see the entire field name that SEED is defaulting to without going into the SEED Header field and moving your cursor to the right in that field to discover what the mapping really is. 

It seems like letting the user expand that column to the size needed to see the longest field would be ideal 

Options could include
* Ability of the user to expande the field to whatever width they desire by pulling on the right hand side of the header of the column (like in other lists).
* Double right click on the right hand side of a column in Excel which causes the program to expand that column to the size that fits the largest data for that column. But even without that fan

### PR DESCRIPTION
**Pull request by axelstudios**
#### What's this PR do?
Allows the mapping columns to be resizable with drag handles
#### How should this be manually tested?
Upload a file, go to the mapping page, drag the column dividers to resize
#### What are the relevant tickets?
fixes #1337

### CODE REVIEW

**Comment by nllong** [comment]
This doesn't appear to be working. Disabled cache, hard refresh. class looks right on the column.

image

**Comment by axelstudios** [comment]
@nllong Here's what I see when I drag on the column handles:
video_2018-03-13_172203

**Comment by nllong** [comment]
That’s what I was expecting. I can show you tomorrow

**Comment by nllong** [comment]
Works on mac with an external display. There may be an issue using the laptop display. Approving.

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- let me know when these various PRs are on one of your dev servers and I will test.

**Comment by axelstudios** [comment]
@RDmitchell Just deployed `develop` to dev1

**Comment by nllong** [comment]
FYI @RDmitchell  -- we will move items into the Test bucket on the [github project page](https://github.com/SEED-platform/seed/projects/3)

**Comment by RDmitchell** [comment]
Perfect. I'll test and close if they are fixed.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 51231c0
Files:
* Issue 1597-long field names (ESPM).xlsx
* Issue 1597-short field names.csv
Located in this folder
https://drive.google.com/open?id=1FjHCwMcRkrmbQMEJfcSvfYYIm-kgkKlQ

I think that this feature isn't working well enough for the case that it was designed to help, ie, an ESPM file with lots of very long fields. See the 2nd example, and try importing the file above called 
Issue 1597-long field names (ESPM).xlsx

I'm not sure what the solution is -- maybe allow truncating of the ROW data, or add a horizontal scroll bar (?)

The first time I tried this feature, the right hand side of the SEED Header field wouldn't move at all, even though I could see the double horizontal arrow. So I ran developer tools on with disabled cache and it worked. 

Then I tried a file that had short field names (and only 1 record) and I could stretch the SEED header column to a very wide width. Then I tried it with an ESPM file, and I couldn't expand the column very much because the file had long field names in both the SEED Header column and the Data File Header column as well as in the ROW columns. See the examples below.

Here is what I can do for the sample file that has very short file names -- And I think since there was only 1 record in the file, I could expand the field very far. But this is not really a valid test since it only has 1 record.
image
But for the ESPM file, which is really the problem case, since all users are going to be importing and mapping these files, the field names can be quite long, and the data in the ROW columns is also long, so I was not able to expand the SEED Header column very far at all.
image

**Pull request merged**
