### PR TITLE
feat(ci): use github actions for ci

### PR DESCRIPTION
**Pull request by macintoshpie**
#### Any background context you want to provide?
Travis is mean, and this is a temporary workaround.
EDIT:
Travis is forcing public repos to move from .org to .com, see here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration
We moved seed's repos to the .com site, and then they announced a new pricing model: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
TLDR; is that you have to request credits now if you're OSS, I reached out to them about this but haven't heard back yet.

Important part:
> Building on a public repositories only
We love our OSS teams who choose to build and test using TravisCI and we fully want to support that community. However, in recent months we have encountered significant abuse of the intention of this offering (increased activity of cryptocurrency miners, TOR nodes operators etc.). Abusers have been tying up our build queues and causing performance reductions for everyone. In order to bring the rules back to fair playing grounds, we are implementing some changes for our public build repositories.

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
You will not need to change your build definitions when you are pointed to the new plan
When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
Your account name and VCS provider (like travis-ci.com/github/[your account name] )
How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)
Usage will be tracked under your account information so that you can better understand how many credits/minutes are being used
#### What's this PR do?
Runs django tests and flake8 using github actions instead of travis. This might not be our long term solution (using github actions), but it will at least keep us rolling for a bit.

What this does _not_ include is:
- functional tests
- tox api test
- tox docs test
- coveralls integration
- some django tests which hit the PM site, we need to add the SEED_PM_UN and SEED_PM_PW to our repo's secrets, see here: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

### CODE REVIEW

**Review by nllong — COMMENTED** [review]
So this will run in parallel with the other travis.ci tests? And this run entirely on GH?

**Comment by nllong** [comment]
> So this will run in parallel with the other travis.ci tests? And this run entirely on GH?

And this seems like a direct competitor to Travis... which maybe is a good thing?

**Comment by macintoshpie** [comment]
> > So this will run in parallel with the other travis.ci tests? And this run entirely on GH?
> 
> And this seems like a direct competitor to Travis... which maybe is a good thing?

Yes this will run in parallel with travis, for now. We should remove the protection requirement of Travis passing and add the requirement for Github actions to pass (until we get our CI sorted out)

**Comment by macintoshpie** [comment]
Note that adding coveralls to the process would be pretty trivial, we'd just need to add the coveralls repo token to the secrets (which I don't have permission to do), see here: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by adrian-lara** [comment]
I'd be good with implementing this for now as to not hold up any ongoing development. 

We can figure out a long-term solution (maybe this ends up being it) in separate conversations.

**Review by adrian-lara — APPROVED** [review]

**Pull request merged**
