### PR TITLE
OGBS - French (Canada) localization

### PR DESCRIPTION
**Pull request by rgm**
#### Any background context you want to provide?

To be acceptable for use in Canada, the user interface must be available in both official languages: French and English.

#### What's this PR do?

This PR extends seed to use browser `Accept:` headers to deliver `fr-CA` (or, effectively as a no-op, `en-US`) language localization. User interface strings are being managed at [lokalise.co](https://lokalise.co/project/3537487659ca9b1dce98a7.36378626/?view=multi) on their free enterprise account for open source projects; please contact @rgm for access.

(Date/currency/number localization (eg `1 000,00$` or `12 Mai 2017`) is not addressed here and will be taken up in another PR).

Two significant outstanding issues for discussion, semi-related:
1. Minor XSS vector through the `sce` sanitization strategy
2. Handling column names ... just leaving untranslated for now and will handle as part of sorting out the remainder of the Pint column name work.

#### How should this be manually tested?

1. Flip your browser's preference to put `fr` or `fr_CA` as the top preference.
2. Reload SEED.
3. Browse the site, trying out normal workflows.
4. Flip browser's preference back to `en_US` or just entirely reset browser.

Expected behaviour:

All UI strings should appear in French or English as chosen. There should be no English in the French run-through; this would indicate a missing string in the localization file as the UI will fall back to English if the French string is missing. There should be no strings of the sort `ALL_CAPS_SHORT_DESCRIPTION_OF_CONTENT` in either English or French; this would indicate that the translation has failed entirely.

#### What are the relevant tickets?

n/a.

#### Screenshots (if appropriate)

screen shot 2017-11-06 at 23 07 18
screen shot 2017-11-06 at 23 07 55
screen shot 2017-11-06 at 23 08 24
screen shot 2017-11-06 at 23 06 44

#### Definition of Done:
- [ ] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [ ] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [ ] Does this PR require a regression test? All fixes require a regression test.
- [x] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

Yes, package.json and bower.json both contain the new dependencies. Nothing new has been added in the Django layer.

### CODE REVIEW

**Comment by rgm** [comment]
So I'm seeing the two big remaining items on this:

- Figure out this XSS vector issue
- Get the angular tests running again.

I'll get going on both; I think I've talked myself into going with an `escapeParameters` sanitization strategy on the XSS but I'll try it out and confirm.

**Comment by rgm** [comment]
Per @kflemin

> Hi Ryan, I’ll let @axelstudios confirm, but this all seems reasonable to me.  
We have mostly used forms 1 and 2 tags in the past, with a bit of form 6 to translate toastr messages.

**Comment by axelstudios** [comment]
Hey Ryan - the changes looked great.  I only found a couple issues, so I added those fixes and some one-time binding improvements to a PR for your branch: https://github.com/opengreenbuilding/seed/pull/5

Each translate filter adds another Angular watcher to the digest cycle, but that can be avoided by either making them one-time bindings with `::` or by using the translate directive.

**Comment by rgm** [comment]
@axelstudios those are great changes, merged & thanks. Didn't know that about Angular but will watch for it in future. I'll add the note to `translation.md`.

**Comment by rgm** [comment]
Huh, _quelle surprise_... a good blog post about one-time binding (ie. the double-colon in `{$:: 'thing' | translate $}` was written by the guy who wrote angular-translate: 

https://blog.thoughtram.io/angularjs/2014/10/14/exploring-angular-1.3-one-time-bindings.html

**Pull request merged**
