### PR TITLE
Fix email

### PR DESCRIPTION
**Pull request by haneslinger**
[

### CODE REVIEW

**Comment by axelstudios** [comment]
- [ ] Don't downgrade `package-lock.json`

**Comment by nllong** [comment]
This seems close, but when I select only a single property, then no data are sent. If I select two items in the inventory, then the first is selected. It feels like we have an off by one issue.

To test, by default the emailer is your console. So if you had an email address to a property's `owner_email` field and add the following email template in the http://127.0.0.1:8000/app/#/accounts/10/email_templates config, then when you select and run, it will show up in your console.

```
Hello owner of {{ubid}}!

You have a square footage of {{gross_floor_area}}.

Enjoy!
```

**Comment by haneslinger** [comment]
@nllong, I don't see the emails in my console, but I do see log that imply both selected properties were sent emails
```
seed_web       | [INFO]2024-04-23 09:38:45 PID 15: Process finished, 2 attempted, 2 sent, 0 failed, 0 requeued
seed_web       | 2024-04-23 09:38:45 INFO     Process finished, 2 attempted, 2 sent, 0 failed, 0 requeued
seed_web       | [INFO]2024-04-23 09:38:45 PID 15: 2 emails attempted, 2 sent, 0 failed, 0 requeued
seed_web       | 2024-04-23 09:38:45 INFO     2 emails attempted, 2 sent, 0 failed, 0 requeued
```
are you sure both of your selected properties have emails?

**Review by nllong — APPROVED** [review]
Sweet after fixing the ID to property view, then all worked.

**Pull request merged**
