### PR TITLE
allow 255 items in label list

### PR DESCRIPTION
**Pull request by nllong**
#### Any background context you want to provide?
List of labels to filter were limited to only 25 items

#### What's this PR do?
Expands the filter list to 255 items

#### How should this be manually tested?
add more than 25 labels and make sure that they show up in the building list filter by label box

#### What are the relevant tickets?
#989 

#### Definition of Done:
- [X] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.) No
- [X] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [X] Does this PR require a regression test? All fixes require a regression test. No
- [X] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated? NO

### CODE REVIEW

**Comment by RDmitchell** [comment]
Thanks Nick !!

**Comment by mmclark** [comment]
loaded on seedtest

**Comment by RDmitchell** [comment]
@mmclark -- did this ever get loaded onto production? If not, we should get it up there. Thanks.

**Comment by RDmitchell** [comment]
Tested on production, works great !

**Pull request merged**
