### PR TITLE
In superuser organization list (under Admin) show the Organization ID…

### PR DESCRIPTION
**Pull request by tallus**
… from the database in a column
    - added column to template in static/seed/partials/admin.html
    - altered width of last column to fit

#### What's this PR do?
Adds an ID column to the Remove buildings and organizations of the admin screen
#### How should this be manually tested?
Visit /app/#/profile/admin as a superuser
#### What are the relevant tickets?
#984 
#### Screenshots (if appropriate)
selection_133
#### Definition of Done:
- [ ] Passes manual testing is different browsers

### CODE REVIEW

**Comment by RDmitchell** [comment]
Paul -- sorry that I wasn't clearer about where the ID comes from -- it needs to be the official organization ID that is in the database. So for example, I believe that New York City is ID # 49, City of Cambridge is ID # 69, etc. Thanks !

**Comment by tallus** [comment]
Would that be parent_organization_id? At the moment  it's the the id taken from the organization_org table.

**Comment by RDmitchell** [comment]
Yes I believe that is correct.

**Comment by tallus** [comment]
New Screenshot:
selection_134

N.B. parent_org_id can be a null field

**Comment by RDmitchell** [comment]
Can you show a screen shot that shows the Parent Org ID?

@StephenCzarnecki -- is parent org ID the right ID?

**Comment by tallus** [comment]
Here you go:
selection_135

According to the Organization model (or at least its get_parent method) an org is its own parent if its not a sub-organization, so I have followed the same principal here. i.e. it will show its own id if its a parent, its parents id if it is a sub-organization

**Comment by RDmitchell** [comment]
do you think it is worth having two columns, one for Parent and one for child, with the appropriate IDs or blanks ? Then it is completely clear what IDs are what ?? Not sure.

**Comment by tallus** [comment]
I wondered about that. There's an is_parent field we could display, or we could use id & parent_id -- it shouid be clear what's going on if they match.

**Comment by tallus** [comment]
Some like:
Parent Id | Has Children
23&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  | &#x2714;

or 
Parent Id | ID
23&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  | 23
23&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  | 24

**Comment by RDmitchell** [comment]
Let's go with the second option

Thanks !

**Comment by tallus** [comment]
selection_136

**Pull request merged**
