### PR TITLE
Issue #897 - Remove unused pip packages

### PR DESCRIPTION
**Pull request by nicholasserra**
#### What's this PR do?
Removes over 20 unused python packages. Removes a couple `reconcile` files that were not used. Removes references to New Relic.

#### What are the relevant tickets?
Refs #897 

#### Definition of Done:
- [x] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [x] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [x] Does this PR require a regression test? All fixes require a regression test.
- [x] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

### CODE REVIEW

**Comment by nicholasserra** [comment]
@mmclark I ended up just going with a simple `aws.txt` for server requirements. Replaces production.txt

**Comment by mmclark** [comment]
Looks like the spelling job if failing in Travis.  Likely not a big issue, but it would be good to have it passing.  What's the fix for this?

**Comment by nicholasserra** [comment]
Hoping @nllong can tell me how to rebuild those sphinx docs, as they need updated to clear that error.

**Comment by nllong** [comment]
well it looks like the spelling is doing its job. The issue is this line: https://travis-ci.org/SEED-platform/seed/jobs/122371686#L519

regex isn't a real word I guess. Add it to the list here: https://github.com/SEED-platform/seed/blob/develop/docs/source/spelling_wordlist.txt

It is also warning us about some other things that I was hoping would resolve automagically when we upgrade to django 1.8. Regardless, if you fix regex, it should pass.

**Comment by nicholasserra** [comment]
What's up with all the import errors? I removed some python files, and the docs are trying to import them? Do you know how to regenerate the autodoc or should I manually edit it?

**Comment by nicholasserra** [comment]
Also the word "regex" has been in the source all along, it wasn't added in this PR.

**Comment by nicholasserra** [comment]
@mmclark this is green now, should be fine to merge.

@nllong thanks for the look. I think there's still some weird stuff going on with spelling step, but we can revisit later.

**Comment by mmclark** [comment]
loaded on seedtest

**Pull request merged**
