### PR TITLE
3199 feat/add espm import path

### PR DESCRIPTION
**Pull request by Ryoken**
#### Any background context you want to provide?
See ticket.

#### What's this PR do?
Adds support for importing more types of meters from PM "Data Reuest" exports.

#### How should this be manually tested?
Upload this [dummy data](https://github.com/SEED-platform/seed/files/8636287/SEED.Meter.Data.-.From.ESPM.Data.Request.xlsx) and also upload the meter information.
 - verify you have 6 meter types
 - verify 0's in monthly data
 - verify help text when a meter is selected

#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/3199

#### Screenshots (if appropriate)
Screen Shot 2022-05-05 at 3 54 27 PM

### CODE REVIEW

**Comment by nllong** [comment]
@Ryoken  -- it may be easiest to copy over the .pre-commit-config and run it on the en_US/fr_CA files, then merge in your changes! SORRY!

**Comment by nllong** [comment]
oh, it looks like you resolved the conflicts. I was just seeing that almost every line in the language files were conflicting. It think this is all good now!

**Comment by RDmitchell** [comment]
@Ryoken -- has this been deployed to dev1? That is where I am testing importing propane meters.

**Comment by RDmitchell** [comment]
@Ryoken -- should I be able to import this file from ESPM that has a specific meter called Propane? 
image

[Jemez Day School wMeters-ESPM.xlsx](https://github.com/SEED-platform/seed/files/9023794/Jemez.Day.School.wMeters-ESPM.xlsx)

**Pull request merged**
