### PR TITLE
Show link for properties map page

### PR DESCRIPTION
**Pull request by adrian-lara**
#### Any background context you want to provide?
This only shows the property map page and not the tax lot map page.

#### What's this PR do?
Shows link to property map page

#### What are the relevant tickets?
#1982

### CODE REVIEW

**Comment by adrian-lara** [comment]
@nllong and/or @axelstudios 
I noticed the tax lot map page is no longer a part of the app. I just wanted to confirm with the both of you that these changes were intended.

**Comment by nllong** [comment]
Hmm. I don’t think this was intentional. Any else want to chime in on this?

Nick

Da: Adrian Lara <notifications@github.com>
Risposta: SEED-platform/seed <reply@reply.github.com>
Data: lunedì dicembre 9 2019 11:49
A: SEED-platform/seed <seed@noreply.github.com>
Cc: Nicholas Long <Nicholas.Long@nrel.gov>, Mention <mention@noreply.github.com>
Oggetto: Re: [SEED-platform/seed] Show link for properties map page (#2037)


@nllong<https://github.com/nllong> and/or @axelstudios<https://github.com/axelstudios>
I noticed the tax lot map page is no longer a part of the app. I just wanted to confirm with the both of you that these changes were intended.

**Comment by adrian-lara** [comment]
Looks like the initial removal happened here:
https://github.com/SEED-platform/seed/pull/1854/files#diff-eef368813e19cb16e66b4f8f55ccb856R1099

**Comment by RDmitchell** [comment]
I don't actually know what page we're talking about so I can't really comment.

**Comment by adrian-lara** [comment]
@nllong - I'm not quite sure how long it'll take me to make the appropriate changes to enable a dedicated tax lot map page. If I had to guess, it'd be 8-16 hours. Details below.

It looks like the previous removal of the tax lots map page was done to render **related** tax lot information on the dedicated property map page. It sounds useful and is probably a feature that should stay in. But on first pass, it looks like the inventory map page controller code was updated under the assumption that properties are the only inventory type that can have its own dedicated map page. It'd take some time/research to understand the current set up and and make changes appropriately.

**Comment by nllong** [comment]
Maybe we should just leave the page as is then. That is, show related tax lots when viewing properties. We can add a tax lot page later if needed. What do you think @adrian-lara?

**Comment by adrian-lara** [comment]
@nllong Agree - seems like a good path forward given the circumstances. I'll update this branch with latest develop once you merge PR 2034.

**Comment by nllong** [comment]
sounds good. Waiting on CI for #2034.

**Comment by nllong** [comment]
@adrian-lara -- ready for your magic.

**Comment by adrian-lara** [comment]
This is already ready 😄
Showing the property map page was the only change I made initially. Whenever the CI tests finish, it's ready for your review. I'll create the tax lot page issue though.

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong  -- can you tell me what page(s) you are talking about that no longer have the links?

Is it the detail view, where if you are in Property Detail, the related tax lots are shown at the bottom, and vice versa? And if yes, then this latest release will only have that showing on Property Detail and not on the Tax Lot Detail page (ie, no property links showing?)

If this is the case, I think this is something that should get fixed not too long after this release, if possible. It's a drag to have features get taken away.

**Comment by nllong** [comment]
These were the map pages that were not visible to the public. We are going to add a tab to display the map in the next release. The issue was that we used to have a tax lot and a property page (even though they weren't public). Not we only have a single map with both properties and related tax lots.

**Comment by RDmitchell** [comment]
ah, ok, thanks.

**Pull request merged**
