### PR TITLE
Add helper text to Audit Template settings

### LINKED ISSUE #3374: Add helper text to Audit Template settings
Add description text and URLs for how to get these information.

Image

### PR DESCRIPTION
**Pull request by anchapin**
#### Any background context you want to provide?
Adding helper text.

#### What's this PR do?
References the "AUDIT_TEMPLATE_HOST" in settings to bring in the base url for Audit Template API page.

#### How should this be manually tested?
Go to an Organization's settings page and click on "API Key". Check that the Audit Template fields have helper text and make sure the links work as intended.

#### What are the relevant tickets?
Fixes #3374

#### Screenshots (if appropriate)
image

### CODE REVIEW

**Review by Ryoken — COMMENTED** [review]
Could these new texts get translations from lokalise?

**Comment by anchapin** [comment]
That's a good idea. However, do you know how I handle a translation of text that has a href in the middle of it? For example, do I need to split it into two or three different lokalise keys or will it work if it is all one?

**Comment by Ryoken** [comment]
@anchapin Here's an example of a dynamic translate that has text passed in to it:
Screen Shot 2022-07-28 at 10 43 47 AM

**Review by Ryoken — APPROVED** [review]
looks good!

**Pull request merged**
