### PR TITLE
Issue #651 -  export buildings error

### PR DESCRIPTION
**Pull request by nicholasserra**
#### What's this PR do?
Fixes an issue on building export when there are a lot of buildings in the file. Fixes the building count during the progress bar view.

Basically, the download url was being hit before the file was completely saved to disk, throwing a 500. Added a status to show that the file is not ready, and added delay and retries to the FE view.

#### What are the relevant tickets?
Refs #651 

#### Screenshots (if appropriate)
screen shot 2016-01-18 at 4 17 01 pm

### CODE REVIEW

**Comment by RDmitchell** [comment]
Do we know why the tests have failed?

**Comment by nicholasserra** [comment]
Tests are failing in the develop branch.

**Comment by nicholasserra** [comment]
Looks to be something with flake8. I'll look into it.

**Comment by nicholasserra** [comment]
Merging #664 should fix this.

**Comment by nllong** [comment]
#432 has some flake8 fixes as well. Hopefully it fixes travis.

**Comment by nicholasserra** [comment]
This is now passing.

**Comment by RDmitchell** [comment]
I think that Miles plans to merge the outstanding PRs either today or tonight.

**Comment by RDmitchell** [comment]
@nicholasserra -- I imported a data file with 6115 records, and when I tried to export them, I got a 400 (BAD REQUEST) error. I will put a data file reference in Slack for this
image

**Pull request merged**
