### PR TITLE
Merge bricr-dev into develop (attempt 2)

### PR DESCRIPTION
**Pull request by adrian-lara**
This reverts commit a3b9fefffef68e80e5ca5aba520d984f4e3f24a1, which was inadvertently merged before thorough testing was conducted.

#### Any background context you want to provide?
This is basically re-opening PR #2130

#### What's this PR do?
Per the previous PR, 
>Merge latest changes from BRICR Dev into the development branch.
This branch has no conflicts with develop.

#### Testing
Since the changed code and related new features were already reviewed when `bricr-dev` itself was updated, I focused my code review on logical conflicts with existing `develop` code.

As far as manual testing, my own testing consisted of monkey testing the importing and viewing of Portfolio Manager meters, BuildingSync scenario meters, and GreenButton meters.

#### What are the relevant tickets?
#2131

### CODE REVIEW

**Comment by adrian-lara** [comment]
@macintoshpie tagging you here to review my changes in my most recent 3 commits:
99214f4fabcb77ecfb87d90b5892ea6aadd14135
7030980918476d9e3c003c2dcd3042a56abc142c
2875aceea1991815c0364b7de4f90c4bbc3b9382

Also wanted to ask, was there anything else I should test or review outside of what I mentioned here?
> Since the changed code and related new features were already reviewed when bricr-dev itself was updated, I focused my code review on logical conflicts with existing develop code.

> As far as manual testing, my own testing consisted of monkey testing the importing and viewing of Portfolio Manager meters, BuildingSync scenario meters, and GreenButton meters.

**Comment by adrian-lara** [comment]
@nllong Do you think our testing/review approach was enough here? 

My testing,
> Since the changed code and related new features were already reviewed when bricr-dev itself was updated, I focused my code review on logical conflicts with existing develop code.
> 
> As far as manual testing, my own testing consisted of monkey testing the importing and viewing of Portfolio Manager meters, BuildingSync scenario meters, and GreenButton meters.

and

Per Ted,
> For testing I can't think of anything else to do. I also pulled down the branch and uploaded some BSync, and PM data, and merged them and things seem to be working properly.

**Comment by nllong** [comment]
@adrian-lara -- is this ready to merge?

**Comment by nllong** [comment]
I merged this into develop and tested import and updating buildingsync data. Worked nicely!

Note that the BuildingSync files from AT don't work with this version yet.

**Pull request merged**
