### PR TITLE
remove sync salesforce button due to timeout

### PR DESCRIPTION
**Pull request by kflemin**

### CODE REVIEW

**Review by axelstudios — APPROVED** [review]

**Comment by RDmitchell** [comment]
@kflemin / @axelstudios -- is this a UI change or a backend change?

**Comment by axelstudios** [comment]
@RDmitchell Front-end, it just commented out that button

**Comment by RDmitchell** [comment]
@axelstudios -- is it this button, that I found in Org/Settings/Salesforce/Schedule Daily Update on demostaging that has 2.19.0? Or some other button, which I don't see because it's not there anymore (!).

image

**Comment by axelstudios** [comment]
@RDmitchell Correct, that button _isn't_ there on seeddemostaging.  If you're seeing that your browser may still have old content cached somehow:
image

**Comment by RDmitchell** [comment]
ok, I deleted my cache, and after restarting my browser, it's not there anymore. 

Will users have to also do that? I seem to always ask this question, and never seem to retain the answer.... sigh ...

**Comment by axelstudios** [comment]
Honestly, I have no idea why you experience so many caching issues.  Back in the v2.18.0 release [we changed the headers](https://github.com/SEED-platform/seed/pull/3940) such that all static assets expire after 24 hours, so you should never see any content that was older than 1 day ago.. you can see the expiration for that exact page here from my browser:
image

**Pull request merged**
