### PR TITLE
Nav property on click in property insight page

### PR DESCRIPTION
**Pull request by haneslinger**
#### Any background context you want to provide?
If the points are close to each other and you click two, idk how it picks which you go to 🤷 lmk if you know a fix.
#### What are the relevant tickets?
https://github.com/SEED-platform/seed/issues/3625

### CODE REVIEW

**Review by anchapin — CHANGES_REQUESTED** [review]
I'm not sure why (I tried tracking it down to no avail), but when I use this branch I don't see any data points on the graph (see first image below) compared to the develop branch (second image below).

No Data Showing Up
image

Develop Branch
image

**Comment by haneslinger** [comment]
@kflemin would you please check if you experience the same error as chapin? We fixed it with a rebase, but there's no go reason that should have worked.

**Comment by kflemin** [comment]
@haneslinger @anchapin, I just pulled this branch, created a metric (I had none), and now when I navigate to the program insights page (or property insights), the graph doesn't load. I get this error: 
File "/Users/kflemin/repos/seed/seed/models/compliance_metrics.py", line 75, in evaluate
    display_field_id = Column.objects.get(table_name="PropertyState", column_name=self.organization.property_display_field).id
  File "/Users/kflemin/.pyenv/versions/seed-3.9.1/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/kflemin/.pyenv/versions/seed-3.9.1/lib/python3.9/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
seed.models.columns.Column.MultipleObjectsReturned: get() returned more than one Column -- it returned 2!

**Comment by nllong** [comment]
@kflemin  - the multiple objects returned is due to not passing the org id to the column.objects.get call. @anchapin and I found this and fixed it on his branch--not sure if that a PR has been created for it yet though. The TLDR is that the column call will return the total of orgs (so you must have had 2).

**Pull request merged**
