### PR TITLE
Filter By Label By Cycle

### PR DESCRIPTION
**Pull request by axelstudios**
#### What's this PR do?
Filter By Label on the inventory list view previously showed all labels that had been applied to any record from any cycle.  Now, the only labels that appear in the dropdown are ones that can be found on records for the currently selected cycle.

#### How should this be manually tested?
Have records in more than one cycle.  Apply a label to records in one cycle that has not been used for the other cycles.  Change cycles to see that the label becomes available or removed in the label filter.

### CODE REVIEW

**Comment by nllong** [comment]
looks good. tested per your instructions.

**Comment by RDmitchell** [comment]
@axelstudios - I don't think there is a Github issue for this, or a PT story. Seems like we should make one so that it is on my list of things to test .. ??

**Comment by axelstudios** [comment]
Yeah, this was just a bug I stumbled across - I'll add a pivotal ticket

**Comment by RDmitchell** [comment]
@axelstudios - is this deployed to the dev1 server for testing?

**Comment by RDmitchell** [comment]
Actually, looks like it is, because develop and dev1 are both SHA: 8a68345

**Comment by RDmitchell** [comment]
instance: dev1
SHA: c94bc89
org: ID = 69

Added label to Cycle = 2017, and it is the only label that shows up in the Filter by Label box

Going to Cycle = 2016, there are lots of labels applied, and the one I added for 2017 does not appear in that list, and the labels in 2016 do not appear in 2017. 

So seems to be working

**Pull request merged**
