### PR TITLE
[Issue 105] Prevent dismissing of data upload modal dialog box on first ...

### PR DESCRIPTION
**Pull request by meghasandesh**
...file uploaded

### CODE REVIEW

**Comment by mmclark** [comment]
Merged into testing branch, and deployed to seedtest

**Comment by RDmitchell** [comment]
Megha -- I am not sure I am testing this correctly. I start to upload the standard "covered-buildings" data file, click away from the progress bar box, and the dialog box goes away. Maybe I am (again) not testing in the right place. Maybe we can do a webinar and you can show me at what stage I should be testing. Thx. Robin

**Comment by meghasandesh** [comment]
I have not been able to look at this issue again yet. I think the better
solution is to simply abandon the clicking in favor of a 'Cancel' button.
I'll look at this again and have an update out soon.

Megha

**Comment by RDmitchell** [comment]
Sounds good. Thx.

 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by mmclark** [comment]
Megha - can you re-issue this pull request against the develop branch?

**Comment by meghasandesh** [comment]
Miles,

I will be creating a stronger fix for this issue. I think you can close
this pull request for now.

Megha

**Pull request closed without merging**
