### PR TITLE
Removing unnecessary config settings

### PR DESCRIPTION
**Pull request by danielmcquillen**
#### Any background context you want to provide?
The local_untracked.py.dist file hasn't been updated in awhile and it has some old settings that aren't relevant anymore for local development setup.

#### What's this PR do?
Removes old settings. Adds one setting that was missing. This should make it easier to config a local environment when first setting up SEED.

#### How should this be manually tested?
- Git pull the latest develop branch
- Create a new virtual env
- Make sure your `config/settings/local_untracked.py` file follows the config as shown in this .dist file
- Update requirements `pip install -r requirements/local.txt`
- Migrate the database `./manage.py migrate --settings=config.settings.dev`
- Run celery and SEED as before

#### What are the relevant tickets?
#911 

#### Screenshots (if appropriate)
n/a

#### Definition of Done:
- [ ] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [ ] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [ ] Does this PR require a regression test? All fixes require a regression test.
- [ ] Does this add new dependencies? If so, does PIP, npm, bower requirements need to be updated?

### CODE REVIEW

**Comment by danielmcquillen** [comment]
@nicholasserra Does this look good? I pulled out everything that I had deleted when you helped me get the latest up and running, and added in two lines that my config had that I didn't see in this .dist file.

**Comment by nicholasserra** [comment]
That EMAIL_BACKEND you have would only work with smtp settings added. Do you get emails locally? Might want to leave that out, as it defaults to the console backend.

**Comment by danielmcquillen** [comment]
@nicholasserra How's that? Is there anybody else who should look at this?
@mmclark Do you have any comments? I'm just trying to capture what I had to change today to get the latest to run locally.

**Comment by danielmcquillen** [comment]
Hmm. I'm not sure why the build is failing as the file I changed should have an impact. At any rate, if the BE team thinks this is helpful and contains the right settings, please let me know and I'll remove the DO NOT MERGE and in progress labels.

**Comment by nicholasserra** [comment]
There's a bunch of newlines added to the file, if you look at the diff. Probably causing the failure.

**Comment by danielmcquillen** [comment]
Ok, removed newlines. But still getting that error. Surprised, since it's just a .dist file that shouldn't have any impact on that build. Looking at the error, there's something in their about "sauce" not being able to connect and that the build process itself might be broken.

At any rate, this isn't critical and maybe I should just close this PR. I was just trying to make the settings file a bit more up-to-date but it's not a big issue and there are other more pressing things going on.  I'll just close this PR for now.

**Pull request closed without merging**
