### PR TITLE
Add docker volume commands to docker docs

### PR DESCRIPTION
**Pull request by paddatrapper**
#### Any background context you want to provide?
The Docker volumes `seed_pgdata` and `seed_data` are declared as external volumes. These need to be created manually before `docker-compose up` can be run.

#### What's this PR do?
Documents the two commands required to create the volumes

### CODE REVIEW

**Comment by nllong** [comment]
Hi @paddatrapper -- can you follow this process so that we can merge this down?

https://github.com/SEED-platform/seed/blob/develop/.github/CONTRIBUTING.md

Don't overthink the responses when you fill out the document. Also, please cc me when you submit as well. Thanks!

**Comment by paddatrapper** [comment]
@nllong what is your email for me to add as a CC?

**Comment by paddatrapper** [comment]
Also according to CONTRIBUTING, as this is only a small bug fix, I do not need to fill out the document, just send the consent paragraph

**Comment by paddatrapper** [comment]
@nllong I have sent the email

**Comment by nllong** [comment]
Excellent, thank you. I see it in my inbox too. I'll update the word doc with my information as well. I'll merge down your changes shortly! Thanks for helping make SEED successful.

**Pull request merged**
