### PR TITLE
BRICR buildingsync v2.0 import and export

### PR DESCRIPTION
**Pull request by kflemin**
#### Any background context you want to provide?
getting ready for buildingsync 2.0, imports BRICR buildingsync 2.0 files
#### What's this PR do?

- import buildingsync XML v2.0 (as of now) from BRICR project
- still supports Reports.Report or Report
- no changes to UI to handle multiple reports (still expecting a single report even though structure is different)
- added new fields into the scenario table
- importing TimeSeriesData from buildingsync into the meter and meterreading tables (note that all readings are expected to be in kBtu...this seems to be built-into the meterreading table)
- exporting new scenario fields and meter readings to Excel spreadsheet when present

#### What are the relevant tickets?
#1929

### CODE REVIEW

**Comment by nllong** [comment]
@RDmitchell -- do you have any concern if we release 2.8.0 with a preview of BuildingSync version 2.0? I don't think that this impacts any of our existing cities.

**Comment by RDmitchell** [comment]
@nllong -- fine with me. I was going to try testing the Building Sync import feature anyway. I have Building Sync files from the test folder in the code -- will those still work or are there new ones to test ?

**Comment by nllong** [comment]
@RDmitchell -- you will need to use the updated XML files here: https://github.com/SEED-platform/seed/blob/bricr-export/seed/building_sync/tests/data/buildingsync_v2_0_bricr_workflow.xml

**Comment by RDmitchell** [comment]
@nllong -- thanks. I'll do that. Is the latest code on dev1 yet (I assume not, but thought I'd ask). thx!

**Comment by nllong** [comment]
> @nllong -- thanks. I'll do that. Is the latest code on dev1 yet (I assume not, but thought I'd ask). thx!

not yet, planning on having it on dev1 by end of today

**Comment by RDmitchell** [comment]
@nllong -- see my comments in issue #1888

**Pull request merged**
