### PR TITLE
Issue #265 - Django 1.8

### PR DESCRIPTION
**Pull request by nicholasserra**
#### What's this PR do?
Upgrade Django to version 1.8.9

#### What are the relevant tickets?
Refs #265

### CODE REVIEW

**Comment by mmclark** [comment]
@nicholasserra This branch has a conflict.  Could you take a look?

**Comment by nicholasserra** [comment]
@mmclark fixed :)

**Comment by mmclark** [comment]
Loaded on seedtest

**Comment by RDmitchell** [comment]
anything in particular I should test? I am going to work with the NYC data on seedtest today, so should be running it through many areas in the program.

**Comment by nicholasserra** [comment]
Nothing specific, just general stuff working. Thanks!

**Pull request merged**
