### PR TITLE
[Issue #172] Simplify typeahead checking and consequntly also fix dup ch...

### PR DESCRIPTION
**Pull request by meghasandesh**
Fix for Issue #172

### CODE REVIEW

**Comment by meghasandesh** [comment]
Ignore the pull request for now, needs more testing

**Comment by meghasandesh** [comment]
I have tested and uploaded a better solution. 

Miles,

Can you pull this into seedtest?

Thanks

**Comment by mmclark** [comment]
I won't be able to do this until I get back from my trip, but after
that, I'll take care of it.


meghasandesh writes:

**Comment by RDmitchell** [comment]
OK, I have set the milestone in the pull request to the June release (end of June)

**Pull request merged**
