### PR TITLE
Issue116

### PR DESCRIPTION
**Pull request by meghasandesh**
Miles,

This is the new pull request for the typeahead list against develop. Let me know if you still see the conflicts.

Thanks

Megha

### CODE REVIEW

**Comment by RDmitchell** [comment]
Megha 

I am confused about what this pull request relates to. The title says Issue # 116, which is the PM UI issue, but it seems like this is actually for Issue # 139

Maybe you should change the title, change the Issue # and put a better title on it.

**Comment by meghasandesh** [comment]
Yeah, I mixed up the issue numbers. I'll get the merge conflicts resolved.

**Comment by RDmitchell** [comment]
Can this pull request be merged so that I can test it on seedtest?

**Comment by mmclark** [comment]
Megha - perhaps this PR should be closed and you can issue a new one against develop when you're ready.

**Comment by meghasandesh** [comment]
Yes, I will close this now

**Pull request closed without merging**
