### PR TITLE
Upload error handling via cache

### PR DESCRIPTION
**Pull request by axelstudios**

### CODE REVIEW

**Comment by rebrownlbnl** [comment]
Does this fix the problems with PR #224, or which issue(s) is this associated with?
Also, can you add a commit message saying what was changed?
thanks.

**Comment by axelstudios** [comment]
Yes, this is the same as the previous pull request, except that it fixes the issue you were seeing.

This resolves #100, resolves #33, and fixes #88. #86 is related and should be retested.

**Comment by mmclark** [comment]
Great.  I'll merge it and load it on seedtest.

**Comment by RDmitchell** [comment]
Status of issues related to this:

Resolved:
https://github.com/SEED-platform/seed/issues/100
https://github.com/SEED-platform/seed/issues/33 -- I have made a specific issue for some of the importing states that the program should handle
https://github.com/SEED-platform/seed/issues/86 -- closed because this is already in another issue https://github.com/SEED-platform/seed/issues/96

Still outstanding:
https://github.com/SEED-platform/seed/issues/88 -- imports but doesn't saving mapping; that issue is still open

**Comment by RDmitchell** [comment]
Resolved --  https://github.com/SEED-platform/seed/pull/88 -- not sure why it didn't work before, but both Claudine and I have tested it and it works.

So all are resolved.

**Pull request merged**
