### PR TITLE
EEEJ Analysis Functionality

### PR DESCRIPTION
**Pull request by kflemin**
#### What's this PR do?
New EEEJ Analysis 

#### How should this be manually tested?
Add a few buildings (must contain address_line_1, city/state or postal_code)
Select buildings -> Run an Analysis -> select the EEEJ Analysis
Ensure that the analysis is successful
Check that the census tract field identified is correct (can use https://geocoding.geo.census.gov/geocoder/geographies/onelineaddress?form to compare)
Check that the DAC designation is correct (can use https://screeningtool.geoplatform.gov/en/#3/33.47/-97.5 to compare)

#### What are the relevant tickets?
#4207

#### Screenshots (if appropriate)
Screen Shot 2023-08-23 at 9 52 41 PM
Screen Shot 2023-08-23 at 9 52 47 PM

### CODE REVIEW

**Review by nllong — COMMENTED** [review]
Worked pretty well! A few things, some that can probably be pushed out until later.

1. We should have the analysis use the lat/long if it is already in the database, even if the lat/long is manually entered. 
2. Addresses can be wrong and the Census geocoder seems to be more sensitive than engines like google. (e.g., 1101 Madison St vs 1101 Madison Ave.) Google will find the correct location whereas the census encoder will misplace the location.
3. results!

image

4. I love the link to ejscreen, would be nice to download and keep this in SEED and just show as part of the results.
image

**Review by nllong — COMMENTED** [review]
love the udpate to use the lat/long if given... it fixed the coffee shop. Geocoding by a mistyped address was 53035090900

image

**Review by nllong — APPROVED** [review]
This is working for me. I pushed a couple clean ups and there are few comments that can be removed. 

Merge once you review the comments and the tests pass!

💥💯💥

**Comment by kflemin** [comment]
@nllong: Adding a note here that the EJScreen Report is an html report and cannot easily be saved on the SEED side, so we are just providing the link to it for now. We could investigate a way to say it as a PDF in the future with some kind of html to pdf exporter module.

**Comment by nllong** [comment]
The PDF request has come up from Berkeley several times. They want to be able to generate a PDF of the results (BETTER or otherwise), and then push that PDF to a field in Salesforce. Just adding notes, nothing to do at the moment.

**Pull request merged**
