### PR TITLE
Basic authentication uses base64 encoded, not plain strings

### PR DESCRIPTION
**Pull request by tallus**
#### Any background context you want to provide?
The current authentication model makes a number of bad  assumptions about HTTP authentication
#### What's this PR do?
Fixes authentication using api keys
#### How should this be manually tested?
make an api call using basic auth with an api key e.g. requests.get(url, auth=(username, apikey))
#### What are the relevant tickets?
Issue:   #1198

#### Definition of Done:
- [ ] Does this PR require a regression test? All fixes require a regression test.

### CODE REVIEW

**Comment by nllong** [comment]
Looks like this broke a bunch of the tests. Do you know what is going on there?

**Comment by nllong** [comment]
@tallus -- Can you fix the tests on this branch? We want to merge this down soon now that 2.0 is out. Thanks!

**Comment by nllong** [comment]
@tallus can you look at the failing tests?

**Comment by tallus** [comment]
I will push these on Monday

**Comment by tallus** [comment]
I fixed the tests broken by this change, though there are still broken tests unrelated to these changes.

**Comment by nllong** [comment]
I wanted to evaluate this again. I don't understand why we need to base64 the authentication credentials. SEED runs on https, so it should be encrypted. Having to base64 the API credentials seems like an unnecessary burden.

**Pull request closed without merging**
