### PR TITLE
Allow multiple ubids during import

### PR DESCRIPTION
**Pull request by perryr16**
#### What's this PR do?
Allows import files to contain multiple UBIDs separated by semicolons (;). UBIDs separated by other symbols will be treated as a single UBID

#### How should this be manually tested?
Upload a file with multiple UBIDs per property separated by semicolons

#### What are the relevant tickets
#4177

### CODE REVIEW

**Comment by haneslinger** [comment]
Looks good to me!

the mapping page only show one ubid, but its up to you if that feels right
image

**Review by haneslinger — APPROVED** [review]

**Comment by perryr16** [comment]
The logic to split ubids occurs during the mapping step, so by the time the user sees the mapping results the state has already been created, and the ubids have been separated with the last set as preferred. It felt like the least invasive approach, but I'd be happy to look into showing all ubids on the mapping results.

**Comment by RDmitchell** [comment]
@perryr16 -- How does the preferred UBID get picked? Does that happen in the mapping step? 

If it is happening automatically, I think it might be confusing to the user to just see the final UBID in the mapping results screen, if they didn't understand that only one was selected. 

I'm not sure the best way to show the multiple UBIDs on that mapping results screen, but it might be worth thinking about? 

And if it's too complicated at this point, you could go with what you have. 

And, on the other hand, I am pretty sure that most users are not going to want to really understand the UBID world, and not bothering them with the multiple UBIDs when reviewing the mapping results is probably fine !!!

**Comment by perryr16** [comment]
@RDmitchell the first listed UBID will be assigned as the preferred UBID. Displaying all the UBIDs on the mapping as a ';' separated list is possible, but it's a little ugly. I'd vote to table that feature until requested.

**Comment by RDmitchell** [comment]
@perryr16 -- tabling until we get user feedback is fine !!

**Pull request merged**
