### PR TITLE
Dependency update

### PR DESCRIPTION
**Pull request by axelstudios**
### Changes
Updated dependencies, removed unusued dependencies, organized dependencies into bower.
Also fixed bugs and deprecated code.

Fixed landing stylesheets - this should be tested in production to ensure that the relative paths work correctly with the CACHE directory on production.

### Developer instructions
Install the new developer dependencies: `./bin/install_javascript_dependencies.sh`

### CODE REVIEW

**Comment by mmclark** [comment]
@axelstudios I've merged the PR and installed new javascript dependencies.   When attempting to upload a data file (using the "Add more data files" link in the upper right of the screen below), I get an "Unkown provider" error from angular:

screenshot from 2015-11-25 06-30-35

Have you run into anything like this?

**Comment by axelstudios** [comment]
@mmclark I've only seen the opposite problem, where it warns that $modalInstanceProvider is deprecated and to replace it with $uibModalInstanceProvider.  Can you try running `bower update` from the seed directory?

My guess is that we need to restrict the angular-bootstrap dependency in bower.json to 0.14.3 and up.

**Comment by axelstudios** [comment]
https://github.com/SEED-platform/seed/commit/f6b5b8a29a4e863ae5173f22bdd7dcfbf4832642

**Comment by mmclark** [comment]
That solved the problem - thanks.

**Pull request merged**
