### PR TITLE
Fix slow type ahead list

### PR DESCRIPTION
**Pull request by meghasandesh**
Test out fixes to typeahead list

### CODE REVIEW

**Comment by RDmitchell** [comment]
I have tested in seedtest and this is ready to be incorporated into the production version.

**Comment by mmclark** [comment]
Sounds good.  I'll merge it.

**Comment by mmclark** [comment]
This pull request shouldn't be merged, since it references the old branch with Greg's fixes.  PR 134 incorporated Megha's fixes.  This should be closed.

**Comment by RDmitchell** [comment]
Can you close it?

 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by mmclark** [comment]
Yes

**Pull request closed without merging**
