### PR TITLE
changed mapping for hardcoded values, Issue #171

### PR DESCRIPTION
**Pull request by dangunter**
Modified JSON mapping and added test

### CODE REVIEW

**Comment by RDmitchell** [comment]
Make sure that the field names for the 4 "magic" matching fields get placed in the database properly, because I think they are actual field names / columns in the database with fields names having underscores:

Address Line 1 >> address_line_1
PM Property ID >> pm_property_id

I assume that these field names, with underscores, are everywhere in the code, and lots of things will break if we don't do this.

**Comment by RDmitchell** [comment]
In talking to Rich and Miles about this issue, their suggestion was to make sure that the normalization of fields (where they get set to lower case with underscores substituted for spaces), which is where they get translated from the "user readable" fields into the database fields, happens for these new BEDES / PM fields, in particular the address_line_1 and pm_property_id.

Until we have verified that this normalization is happening, I want Miles to hold off on the pull requests. 

For integration testing, are you using Claudine's API scripts? I will forward an email she sent that has them in it.

**Comment by dangunter** [comment]
I ran `python manage.py test` and everything passed (except the py.test ones, but I ran those separately and they passed), except 3 that were skipped.

All I did was change the mapping for 2 fields.

**Comment by RDmitchell** [comment]
Right, just two fields. But probably the two most important fields in the entire application. 

 

Can you run Claudine’s API scripts, which serve as a sort of integration test, to see if they pass? You can email her (CYCustodio@lbl.gov) and she can send you the details of where they are and how to run them. 

 

Robin 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by cycustodio** [comment]
Attached are all of the files you need to run the API script.
It will ask for the following:
hostname --> the name of the output file, usually I would have the date and
which version I ran the test (e.g., seedtest_04062015)
hosturl --> the main url e.g., https://seedtest.lbl.gov
username --> account for web interface
apikey --> this is under the Developer tab in your account details

organizationID --> if you are running this in a development environment
with a single organization this is '1'. If not, I can show you where to get
this.



----------------------------------------------------------------
Claudine Y. Custodio
cycustodio@lbl.gov
510-495-8062 (Office)
Energy Technologies Area
Lawrence Berkeley National Lab
-----------------------------------------------------------------

**Comment by RDmitchell** [comment]
Claudine -- I don't actually see that files were attached to this issue (?). Alternatively you can put them in the repository somewhere.

**Comment by cycustodio** [comment]
I uploaded the zipfile to google drive. 
[Issue 65](https://drive.google.com/a/lbl.gov/file/d/0B5fKMBregb8HbHNrYTA1cDItQUk/view?usp=sharing)

**Comment by dangunter** [comment]
if it's not too much trouble, could you put the files and instructions in
an appropriate place in the tests directory? That way we can all use them
going forward.

**Comment by RDmitchell** [comment]
It's not clear if this particular set of scripts is really appropriate to general testing -- it is designed just to test Issue 65, but has been useful for testing other things. Maybe at some point in the not too distant future Claudine can generalize it so that it is potentially useful for more general testing.

**Comment by cycustodio** [comment]
The mapping works and the data is saved in the correct fields in the database. I used the dang-171 branch in the repo to test mapping for address line and property id using two sample files.  

I uploaded "covered_buildings_sample" as shown, without changing the field name values
cb_upload
Below is payload for the fieldnames that gets saved:
	{"mappings":[["UBI","UBI"],
			["GBA","GBA"],
			["BLDGS","BLDGS"],
			**["address_line_1","Address"],**
			["owner","Owner"],
			["Premises City","City"],
			["State Of Washington Unique Facilities Identifier (UFI)","State"],
			["Zip","Zip"],
			["Property Type","Property Type"],
			["AYB YearBuilt","AYB_YearBuilt"]],
	"import_file_id":1,"organization_id":"1"}

File uploaded without issues. 

In the database the address line is saved in the correct field. 
cb_database

Next, I uploaded the "property-manager-sample". 
pm_upload
Below is payload for the fieldnames that gets saved:
	{"mappings":**[["pm_property_id","Property Id"],**
			["Premises Name","Property Name"],
			["year_ending","Year Ending"],
			["Property Floor Area (Buildings And Parking) (ft2)","Property Floor Area (Buildings and Parking) (ft2)"],
			**["address_line_1","Address 1"],**
			["Premises City","City"],
			["Premises State","State/Province"],
			["Premises Postal Code","Postal Code"],
			["Date Completed","Year Built"],
			["ENERGY STAR Score Assessment Metric Value","ENERGY STAR Score"],
			["Site Energy Use Intensity (EUI) ","Site EUI (kBtu/ft2)"],
			["Total GHG Emissions (MtCO2e)","Total GHG Emissions (MtCO2e)"],
			["Organization","Organization"],
			["generation_date","Generation Date"],
			["release_date","Release Date"]],
	"import_file_id":2,"organization_id":"1"}

File uploaded and buildings matched with the previous data without  issues. 
matched_bldgs

Checked the database for pm_property_id and address_line_1. The buildings with import id '1' are from the covered buildings and the ones with '2' are  from portfolio manager. The canonical buildings (master records containing both of the files' data) are the last 10 buildings. 
pm_database


(Might be worth investigating why there are blank entries created every time a file is uploaded.)

**Comment by RDmitchell** [comment]
Perfect, thanks much Claudine. 

So Miles, you can merge this pull request.

**Comment by RDmitchell** [comment]
Dan -- is there any way that the JSON file for this mapping can be formatted in such a way that it is readable, at least somewhat, by a text editor? Or display-able in the Github code viewer? Right now it is all in one line, which makes it extremely difficult to read. I would like to check what fields are and are not in that file, and right now I am doing a copy/paste into a text editor and then a search and replace to get carriage returns into the file.

**Comment by RDmitchell** [comment]
Never mind. When I look at the file in the dang-171 branch it is fine and readable.

**Comment by RDmitchell** [comment]
I guess the issue is that when I look at the file in the dang-171 branch it is perfectly readable. But when I look at it in the develop branch, it is one long line. Any idea why that would be the case?

**Comment by RDmitchell** [comment]
I have tested this and it appears to be working. Claudine, can you also confirm, and then I will mark this as ready for production.

**Comment by cycustodio** [comment]
It works.

**Pull request merged**
