### PR TITLE
Strict table mappings

### PR DESCRIPTION
**Pull request by axelstudios**
#### What's this PR do?
During mapping, if columns are mapped to both the Property and Tax Lot tables then require at least one matching field from each table
#### How should this be manually tested?
- Upload a file
- Set all columns to `Property`.  There should be an error only if at least one of the 4 required Property fields is not set (Address Line 1, Custom Id 1, Pm Property Id, Ubid)
- Set all columns to `Tax Lot`.  There should be an error only if at least one of the 3 required Tax Lot fields is not set (Address Line 1, Custom Id 1, Jurisdiction Tax Lot Id)
- Set both `Property` and `Tax Lot` columns.  There should be an error if a mapping field for each table is not set.
#### What are the relevant tickets?
#1587

### CODE REVIEW

**Comment by RDmitchell** [comment]
@axelstudios -- should I put 1587 in the Test column in the Project Tracker?

**Comment by axelstudios** [comment]
@RDmitchell No, it's not deployed yet, pending review and merging

**Comment by RDmitchell** [comment]
Right, I'm always jumping the gun. I realized it hadn't been merged after I made that comment. I'll let you put it in the project when you think it's ready !! :)

**Comment by RDmitchell** [comment]
@nllong -- So I guess this didn't make it into the 2.3.2 release?

**Comment by axelstudios** [comment]
@RDmitchell - It did, it's in v2.3.2

**Pull request merged**
