### PR TITLE
3218 feat/refresh metadata

### PR DESCRIPTION
**Pull request by perryr16**
#### Any background context you want to provide?
The OEP connection required the property/taxlot metadata to be refreshed to the current date to enable a record to be sync'd with salesforce

#### What's this PR do?
This PR adds an inventory list 'action' that allows a user to change the selected properties' "updated" timestamp attribute to the current time.

The user will be shown a progress bar as the celery task executes. Upon completion the modal will close and the page will refresh.

#### How should this be manually tested?
To test user experience: 
inventory > select a number of properties > actions > refresh metadata > refresh_metadata > watch progress bar go to 100 and modal will close 

To check actual property values 'updated' attribute (more involved):
```
docker exec -it seed_web /bin/bash
python manage.py shell
from seed.models import PropertyState
PropertyState.objects.get(pm_property_id=<PM Property ID of your choice>).propertyview_set.first().property.updated 
>>> old time 
```
inventory > select property with same PM Property ID > actions > refresh metadata ...
... back to shell 
```
PropertyState.objects.get(pm_property_id=<Same PM Property ID>).propertyview_set.first().property.updated
>>> current time
```

#### What are the relevant tickets?
#3218 

#### Screenshots (if appropriate)

Screen Shot 2022-04-28 at 1 47 39 PM
Screen Shot 2022-04-28 at 1 47 31 PM
Screen Shot 2022-04-28 at 1 47 21 PM

### CODE REVIEW

**Comment by perryr16** [comment]
Based on the `GetPropertyDetailsFromSEED` endpoint, this should be updating the metadata for a `PropertyView` not a `Property`

Snippet from /views/v3/properties.py 
```
    def retrieve(self, request, pk=None):
        """
        Get property details
        """
        result = self._get_property_view(pk)
```

**Comment by perryr16** [comment]
Correction: based on the following OEP connection info screenshot, it looks for the `updated` date on the `Property` model. This PR is ready for review @Ryoken @nllong 

Screen Shot 2022-04-29 at 11 17 26 AM

**Comment by nllong** [comment]
> Correction: based on the following OEP connection info screenshot, it looks for the `updated` date on the `Property` model. This PR is ready for review @Ryoken @nllong
> 
> Screen Shot 2022-04-29 at 11 17 26 AM

Oh good, so this is consistent with what we were expecting.

**Comment by Ryoken** [comment]
Two things.  Should this action also exist in the actions menu for each property?  Also, when I tried updating one of my properties I got this error:

Screen Shot 2022-05-02 at 2 47 57 PM

**Review by Ryoken — APPROVED** [review]
Works after the most recent pull!

**Pull request merged**
