### PR TITLE
Tallus data cleansing

### PR DESCRIPTION
**Pull request by tallus**
#### What's this PR do?
         Adds some code so cleansing works on taxlots and properties
#### How should this be manually tested?
Import and match data
#### What are the relevant tickets?
PT 118891371

### CODE REVIEW

**Comment by tallus** [comment]
Note, not ready to merge yet

**Comment by tallus** [comment]
Note changed to new file names with commit: [fff8f06](https://github.com/SEED-platform/seed/pull/1060/commits/fff8f060852e3631123677e68e21c5986ab4aca1), awating migrations etc for this.

**Comment by nllong** [comment]
@tallus -- looks good. should we merge this into develop? That is did you resolve the "not ready to merge yet" comment?

**Comment by tallus** [comment]
I did, I used the old field names for now and left the new equivalents in a comment

**Pull request merged**
