### PR TITLE
Issue #544 - Added Django timezone support

### LINKED ISSUE #544: Invalid Date in Data Cleansing Screen
I am getting an "invalid date" for the Date Uploaded in the Data Cleansing screen.

image

I have only tested with one file, but will test with others and see if it makes a difference what type of file it is. 

@axelstudios -- I am assigning this to you. thx.

### PR DESCRIPTION
**Pull request by axelstudios**
### Details
This pull request enables Django timezone support and also adds database timestamps to uploaded files.  This fixes #544.

### Update commands
This PR includes a database migration:
```bash
./manage.py migrate
```

### Screenshot
image

### CODE REVIEW

**Comment by nicholasserra** [comment]
We're going to have an issue with migrations. We should probably not merge this until #768 lands, which is a migration reset on data_importer.

**Comment by axelstudios** [comment]
That works for me.  It will be very easy for me to remake this migration

**Comment by nicholasserra** [comment]
You can now merge develop in and remake this migration. Thanks!

**Comment by axelstudios** [comment]
Fixed - everything looks good

**Pull request merged**
