### PR TITLE
Do not map to Property or TaxLot model fields (only PropertyState and TaxLotState)

### PR DESCRIPTION
**Pull request by nllong**
#### Any background context you want to provide?

There are a few fields that map to Property and TaxLot models (not PropertyState and TaxLotState) including campus, created, and updated. These fields were being returned in the mapping suggestions, but the name of the table was invalid (and unmappable).

#### What's this PR do?
* Force the mapping suggestions to map to only PropertyState and TaxLotState fields by forcing the table name in the result.
* This fixes the issue with the invalid mapping column, but it is still **not** advised to use the same name.

#### How should this be manually tested?
See #2015 

#### Screenshots (if appropriate)

Note that if a user still wants to map the fields, then they will get two fields named the same. With one being on the property/taxlot and the other being on the propertystate/taxlotstate. 
image

### CODE REVIEW

**Comment by RDmitchell** [comment]
@nllong -- I don't quite understand how a user, through the GUI, would map to Property or TaxLot models rather than PropertyState or TaxLotState. I assumed that this was all handled "behind the scenes".

Is this an issue when using the API calls because you can map to specific models?

**Comment by nllong** [comment]
It was possible... see #2015. It was definitely an edge case.

**Comment by RDmitchell** [comment]
So this would only happen in the UI if the "table" pulldown list was blank, ie, not set to either table?

The ESPM files almost always contain a Campus field and I have never see the field not set to Property in the mapping screen. But clearly it can happen, I just have never seen it.

**Comment by nllong** [comment]
That’s correct. Yeah it can happen, but it is rare.

Da: RDmitchell <notifications@github.com>
Risposta: SEED-platform/seed <reply@reply.github.com>
Data: venerdì dicembre 6 2019 13:09
A: SEED-platform/seed <seed@noreply.github.com>
Cc: Nicholas Long <Nicholas.Long@nrel.gov>, Mention <mention@noreply.github.com>
Oggetto: Re: [SEED-platform/seed] Do not map to Property or TaxLot model fields (only PropertyState and TaxLotState) (#2034)


So this would only happen in the UI if the "table" pulldown list was blank, ie, not set to either table?

The ESPM files almost always contain a Campus field and I have never see the field not set to Property in the mapping screen. But clearly it can happen, I just have never seen it.

**Comment by nllong** [comment]
@adrian-lara or @axelstudios  -- can you test this one and merge if it looks good?

**Comment by nllong** [comment]
@adrian-lara can you test this and merge if good?

**Pull request merged**
