### PR TITLE
fix: resolve several member permission issues

### PR DESCRIPTION
**Pull request by axelstudios**
#### Any background context you want to provide?
See the related issue

#### What's this PR do?
Improves the logic around whether someone can edit org member roles

#### How should this be manually tested?
- Check that removing a user with only one org doesn't show the modal about deleting the user
- Check that roles are now in hierarchical order (owner -> member -> viewer)
- Check that the following revised rules work as expected:
    - You must be either an `owner` or `member` to see an org's members page (this hasn't changed)
    - Superusers can edit any user's role except for the org owner if there is only one
    - Owners can edit all roles except their own if they are the only owner
    - Members can only edit their own role, and only to change it to "viewer"
    - Non-superusers cannot promote their role
    - Once you demote yourself you no longer see options to promote yourself and the UI reflects your new permissions

#### What are the relevant tickets?
#2677

### CODE REVIEW

**Review by adrian-lara — COMMENTED** [review]
Code changes look good and I tested the different cases mentioned here. Each screenshot shows the items being verified.

Verified without screenshot:
> You must be either an owner or member to see an org's members page (this hasn't changed)
> Check that removing a user with only one org doesn't show the modal about deleting the user


Screen Shot 2021-04-19 at 3 51 28 PM
> Check that roles are now in hierarchical order (owner -> member -> viewer)
> Superusers can edit any user's role except for the org owner if there is only one
> Owners can edit all roles except their own if they are the only owner


Screen Shot 2021-04-19 at 4 07 59 PM
Screen Shot 2021-04-19 at 4 09 05 PM
> Non-superusers cannot promote their role
> Once you demote yourself you no longer see options to promote yourself and the UI reflects your new permissions
> Members can only edit their own role, and only to change it to "viewer"

**Comment by adrian-lara** [comment]
As discussed, I came across two potential bugs.

As a user being removed from my last org by someone else, I'm no longer able to log in. (I can still _delete my own_ last org and be able to log in.)  Until I was added to an **existing** org, I could not log in. I couldn't log in if someone created a new org for me.

Also, 
Screen Shot 2021-04-19 at 4 10 37 PM
per discussion, I couldn't demote myself from owner to viewer.

**Comment by axelstudios** [comment]
@adrian-lara Just made the following changes:
- Allow members to change their role to viewer (enforced by the backend).  Superusers can still change anyone's role for orgs they belong to
- Don't deactivate users with 0 org memberships
- The "Delete User" modal is gone since users aren't deleted or deactivated

**Review by adrian-lara — APPROVED** [review]
Code changes 👍🏽 
Testing 👍🏽 
- I was able to change my role from member to viewer as a non-superuser.
- Upon being removed from my last org (by someone else), I was still able to log in. (I'm now prompted to go through the new org flow like any other org-less user.
- There's no longer a delete user modal when a user is being removed from their last org.

**Pull request merged**
