### PR TITLE
#2515 feat: track updates to progress data on frontend

### PR DESCRIPTION
**Pull request by macintoshpie**
#### Any background context you want to provide?
When users are importing/mapping large files some users think SEED is broken b/c we aren't updating the progress bar.

#### What's this PR do?
Adds a note to the geocoding/mapping progress bar which will appear to users if the progress hasn't been updated recently.

#### How should this be manually tested?
Import a large file (or add a long time.sleep in seed.data_importer.match.match_and_link_incoming_properties_and_taxlots). and when mapping (which should take a while) you should eventually (after 1 minute of starting the matching task) see the notice shown in the screenshot below.

#### What are the relevant tickets?
This is a bandaid for #2515 , doesn't fix it as well as we might want but is a nice thing to have for now.

#### Screenshots (if appropriate)
Screen Shot 2021-01-26 at 4 17 49 PM

### CODE REVIEW

**Comment by macintoshpie** [comment]
@RDmitchell @adrian-lara 
The gist of this change is that if the progress bar isn't updated after 1 minute, we show that message seen in the screenshot. Do either of you have a better feeling for how long we should wait to show the message, or if 1 minute is good enough?

**Comment by RDmitchell** [comment]
See also #2550 which is a different problem but not sure what the status bar should do in that circumstance, because it will never display anything other than 0% (at least I think that is true).

**Comment by RDmitchell** [comment]
@macintoshpie -- you might want to look at #2550 because I think that's a case where it will never actually show any other status than 0% because of timeout issues (possibly) on the server, even though the matching and mapping is still happening. 

You might want to consult with @axelstudios about this, as I think he was looking into that issue.

**Review by adrian-lara — APPROVED** [review]
Works as expected. I'll approve for now, as I think this is a reasonable "band-aid". Feel free to re-request if this temporary solution is updated in some way.

**Pull request merged**
