### PR TITLE
545 return key submits filter

### PR DESCRIPTION
**Pull request by danielmcquillen**
https://github.com/SEED-platform/seed/issues/545, #639, https://github.com/SEED-platform/seed/issues/646

### What was wrong?

It's tedious for the user to click on the "update filters" button every time she changes a field in a buildings list table. 

Also, the filters on the 'Matching' table haven't been updated and still had the old called-on-every-keystroke behavior.

Finally, a small filter / results page bug was causing trouble when filtering on a results page other than 1 (#646).

### How was this fixed?

Updated the buildings table to call an enter-key-pressed function, which then decides how to update filters (project buildings or buildings). This included creating a new directive to handle an ENTER keypress in an input field. 

This new directives was also added to the filter fields in the matching list table and the related controller was updated in order to give the matching buildings list view the same behavior as the buildings list, project buildings list, and mapping buildings list.

Finally, the `building_list_controller` and `mapping_controller` were updated to use search_service's `filter_search` method rather than its `search_buildings` method.

## Notes

Currently we have some directives that have the old 'be' (Building Energy) prefix, and others which don't have a prefix at all.  We probably should be using a project-specific prefix for things like directives, so I started a convention of using 'sd' for SEED on the new directive `sdOnEnterKey`. Crazy? Good idea? Thanks for any feedback.

## Animal pic

image

### CODE REVIEW

**Comment by danielmcquillen** [comment]
I noticed while implementing this that I missed the Mapping view when updating the filters to avoid submitting on every keypress.

**Comment by rebrownlbnl** [comment]
I think your proposed naming convention for directives makes sense.
Should we make a pass through all the FE code to update to the new convention?

**Comment by danielmcquillen** [comment]
Yes, Rich, that wouldn't take long. There are nine directives that would need updating. I can create an issue and separate pull request if you'd like.

**Comment by RDmitchell** [comment]
Yes, go ahead and do this.

**Comment by danielmcquillen** [comment]
Ok, I created a separate issue for refactoring directive names. https://github.com/SEED-platform/seed/issues/641

In the meantime, I did include the fix to the building matching table filters in *this* PR, as it's directly related to the work and uses the new directive created in this PR.

**Comment by danielmcquillen** [comment]
Note that this function is probably a good example of where we need a progress indication (as we were discussing at the end of 2015). Right now there's no indication of what's happening after you hit Enter or click the Update Filters button.

**Comment by danielmcquillen** [comment]
This is almost good to go. I just want to test it a bit more tomorrow to see if I can break it.

**Comment by RDmitchell** [comment]
@danielmcquillen -- This is labeled DO NOT MERGE and In Progress. Can you remove those labels if it is ready to be merged, so that Miles will know the status of this PR? thx Robin

**Comment by RDmitchell** [comment]
agreed. But we will have to put this off until after the Feb release. #607 (add spinner) is tagged with the June 2016 release milestone

**Comment by danielmcquillen** [comment]
I missed the fact that a directive already existed for enter-key submits, so I updated the naming to sd prefix and changes all references to use that directive.

**Pull request merged**
