### PR TITLE
Redis backend update

### PR DESCRIPTION
**Pull request by axelstudios**
#### Any background context you want to provide?
The dependency we were using to leverage Redis as the Django/Celery cache (`django-redis-cache`) effectively hasn't been updated since 2020, and requires `redis-py < v4.0`. Redis-py introduced cluster-mode in v4.1.0.

#### What's this PR do?
Drops the `django-redis-cache` dependency in favor of `django-redis`, which is compatible with current versions of `redis-py`. This PR also adds `hiredis` for performance.

Once we migrate to Django v4 we can use Django's built-in Redis support going forward.

#### How should this be manually tested?
1. `pip install -r requirements/base.txt`
2. Update your local config (usually `local_untracked.py`), **see the migration steps below** to understand what to change
3. Test that SEED and Celery work as expected

#### What are the relevant tickets?
#4375

## BREAKING CHANGE
This updated dependency requires users and deployments to modify their `CACHES` config. [Django v4 uses the same syntax](https://docs.djangoproject.com/en/4.2/topics/cache/#redis), so this is a necessary step regardless.

### Migration Steps
1. Update your dependencies with `pip install -r requirements/base.txt`
2. Update the CACHES `BACKEND` property to `django_redis.cache.RedisCache`
3. Update the CACHES `LOCATION` property to match the redis-py native URL notation for connection strings, including the `redis` protocol and database number. e.g. `redis://localhost:6379/1`
    1. Since the `CELERY_BROKER_URL` setting must also be in the same format, it may be helpful to configure that setting first and then reference it in the caches `LOCATION` parameter.

#### Example migration
In your Django settings file, replace existing code that looks like this:
```python
CACHES = {
    'default': {
        'BACKEND': 'redis_cache.cache.RedisCache',
        'LOCATION': 'localhost:6379',
        'OPTIONS': {'DB': 1},
        'TIMEOUT': 300
    }
}

CELERY_BROKER_URL = 'redis://%s/%s' % (
    CACHES['default']['LOCATION'], CACHES['default']['OPTIONS']['DB']
)
```

with this:

```python
CELERY_BROKER_URL = 'redis://localhost:6379/1'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': CELERY_BROKER_URL,
    }
}
```

For advanced connections, the connection string can also specify SSL, username, and password, e.g. `rediss://username:password@localhost:6379/1`

### CODE REVIEW

**Comment by kflemin** [comment]
@nllong what do you think?

**Review by nllong — APPROVED** [review]
Looks good. Let's bring this up on our next call that users will need to update their local untrack files before we merge down.

**Comment by axelstudios** [comment]
```[tasklist]
### TODO
- [ ] Let users know they'll have to update their local configs once this PR merges
```

**Comment by kflemin** [comment]
@dhaley will test this out around Feb12th to make sure it works on stratus before merging.

**Pull request merged**
