### PR TITLE
Fix display name

### PR DESCRIPTION
**Pull request by haneslinger**

### CODE REVIEW

**Review by kflemin — APPROVED** [review]
works great!

**Comment by RDmitchell** [comment]
@haneslinger -- what did this fix? Was it something that the user would see?

**Comment by haneslinger** [comment]
On the analysis page, in the "by property" tab, the display names of the properties was broken. This fixes that. 

So the user will see it, but it's more a fix than a change.

**Comment by haneslinger** [comment]
nope, it's been there

**Comment by RDmitchell** [comment]
Looking at that tab, it's a bit confusing. I think I might write up an issue to see if it can be enhanced to possibly be more useful. 

Thanks

**Pull request merged**
