### PR TITLE
Typeahead fix

### PR DESCRIPTION
**Pull request by meghasandesh**
I've made further changes to try and improve performance of the typeahead list.

### CODE REVIEW

**Comment by RDmitchell** [comment]
Miles, I am happy to test this pull request so you can put it on seedtest when it is convenient. 
Thanks
Robin

**Comment by mmclark** [comment]
Megha - This PR was based on master (not develop) and has merge conflicts.  Can you try basing a new branch off of develop and re-issue the PR.  I'm not confident in resolving the conflicts.

**Comment by RDmitchell** [comment]
Megha

If you could try to fix this pull request in the next day or so that would
be great.

Thanks

Robin

On Sun, Mar 15, 2015 at 2:56 PM, Miles Clark <notifications@github.com>
wrote:

> Megha - This PR was based on master (not develop) and has merge conflicts.
> Can you try basing a new branch off of develop and re-issue the PR. I'm not
> confident in resolving the conflicts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/pull/144#issuecomment-81257097>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by meghasandesh** [comment]
I will issue the new pull request right away

**Pull request closed without merging**
