### PR TITLE
Build docker container for accountability branch

### PR DESCRIPTION
**Pull request by nllong**
#### Any background context you want to provide?
Need to build the develop AH containers for deployment

#### What's this PR do?
* Add the AH/develop branch to the list of branches to publish
* Tag and push to docker hub as develop-ah

#### How should this be manually tested?
* After merging this down, this should tag should auto update: https://hub.docker.com/layers/seedplatform/seed/develop-ah/images/sha256-3ad98ac50b6265a4b1011da99678916a8092bb59d01a753fbedcf885013e6dd1?context=repo

#### What are the relevant tickets?
n/a

### CODE REVIEW

**Comment by nllong** [comment]
@haneslinger  -- can you review and merge when you get a chance? I pushed a docker image to dockerhub for now, but it would be good to let this be automated.

**Review by haneslinger — APPROVED** [review]
👍🏻 looks good

**Comment by nllong** [comment]
> 👍🏻 looks good

Any reason why the analysis view would be failing?

```
FAIL: test_list_with_property (seed.tests.test_analyses_views.TestAnalysesView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/seed/seed/tests/test_analyses_views.py", line 166, in test_list_with_property
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

```

**Comment by haneslinger** [comment]
huh, the errror is that the endpoint doesn't exist, but swagger sees it. I'm looking into it.

**Comment by haneslinger** [comment]
https://github.com/SEED-platform/seed/pull/4285

**Pull request merged**
