### PR TITLE
Delete Derived Columns Before Org

### PR DESCRIPTION
**Pull request by axelstudios**
#### Any background context you want to provide?
Organizations couldn't be deleted if they used derived columns

#### What's this PR do?
Deletes derived columns prior to the cascaded-delete of the organization

#### How should this be manually tested?
(Optionally test this workflow beforehand on the `develop` branch to demonstrate the conditions for failure)
1. Create a new organization
2. Create a derived column within that organization
3. Delete the organization from the admin page

#### What are the relevant tickets?
#3676

### CODE REVIEW

**Review by haneslinger — COMMENTED** [review]
This make sense, but wouldn't make more sense to add `on_delete=models.CASCADE` to the foreign key keeping the derived columns from deleting?

**Comment by axelstudios** [comment]
> This make sense, but wouldn't make more sense to add `on_delete=models.CASCADE` to the foreign key keeping the derived columns from deleting?

@haneslinger I wanted to preserve the original intent, which was to prevent users from deleting a column that was being used in a derived column, unless they first manually remove the derived column.

Having said that, it looks like when derived columns were added the handling for this case was skipped, so it still "allows" you to delete a source column of a derived column (it removes the key and contents from all extra_data fields, but the column itself remains)

**Comment by haneslinger** [comment]
> @haneslinger I wanted to preserve the original intent, which was to prevent users from deleting a column that was being used in a derived column, unless they first manually remove the derived column.

that makes sense. 

> Having said that, it looks like when derived columns were added the handling for this case was skipped, so it still "allows" you to delete a source column of a derived column (it removes the key and contents from all extra_data fields, but the column itself remains)

Do we want to make a ticket for that?

**Comment by axelstudios** [comment]
Already created #3701  ;)

**Pull request merged**
