### PR TITLE
Issue #772 test data

### PR DESCRIPTION
**Pull request by nllong**
#### Any background context you want to provide?
The same test data files were in multiple places in the repo. The spelling of Illinois was wrong.

#### What's this PR do?
Removes the redundant data and fixes the spelling.

#### What are the relevant tickets?
Refs #772

### CODE REVIEW

**Comment by nllong** [comment]
@bravacheLBL This PR will most likely affect you the most. I updated your scripts to point to the right location.

**Comment by bravacheLBL** [comment]
Thank you.

**Comment by RDmitchell** [comment]
So now that Illinois is spelled correctly, all the example files out and about are different. Not that it really matters, since this is an isolated set of tests, but the tests won't run with the generic sample data files from other sources

**Comment by rebrownlbnl** [comment]
do you mean sample data files that people keep locally, outside of the repo?

-------------------------------------------------------
Rich Brown
Building Technology and Urban Systems Division
Lawrence Berkeley National Laboratory
Office: (510) 486-5896
Mobile: (510) 502-5968
REBrown@lbl.gov
www.lbl.gov/~rebrown
-------------------------------------------------------

**Comment by RDmitchell** [comment]
yes. Including the sample files that are downloadable from the program. We can fix those up.

**Comment by nllong** [comment]
Now that you say this. I forgot to rezip the sample data. I will do that. 

- nick

**Comment by RDmitchell** [comment]
I am assigning this to myself to test that the sample data that can be downloaded from the program log in screen has these fixes in it (ie, that Illinois is spelled correctly)

**Comment by RDmitchell** [comment]
downloaded the sample data zip file from seedtest and verified that Illinois now has two "L"s rather than just one in both the covered building and PM sample data !!

**Pull request merged**
