### PR TITLE
240 reorg

### PR DESCRIPTION
**Pull request by nllong**
This PR is a complete reorganization of the project. It was done in small chunks. Tests pass, the test_seed_host_api script passes, and general monkey testing pass. 

The major changes that will require developer recalibration are:
* BE folder was moved to config. When starting the server, you should pass in `--settings=config.settings.dev`
* The requirements file are now layered. For production, nothing changes. For development, make sure to run `pip install -r requirements/local.txt`
* The OSX documentation and developer documentation have moved to the wiki
* Set your environment variable `DJANGO_SETTINGS_MODULE` to your desired configuration, e.g. `config.settings.dev`

### CODE REVIEW

**Comment by mmclark** [comment]
It looks like coverage decreased, which is marked as a failed check.  Any issues to be concerned about?

**Comment by mmclark** [comment]
Nick - given the scope of this change, I'm inclined to merge it into a separate branch off of develop, and then merge into develop after we've had a chance to collectively kick the tires.  Any issues with that approach?

**Comment by nllong** [comment]
I'm not worried about the coverage failure at the moment. That number will increase over the next couple of weeks.

I agree with branching off develop and doing the pull request on that branch.

**Comment by mmclark** [comment]
Nick - I've merged this into a separate branch (off of develop).  It's looking pretty good, but there are a couple of test failures.  Not sure if it's my environment, but could you take a quick look?

```
======================================================================
FAIL: test_get_columns (seed.tests.test_views.DefaultColumnsViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/seed/seed/tests/test_views.py", line 258, in test_get_columns
    u'type': u'string',
AssertionError: {u'field_type': u'building_information', u'sortable': True,[162 chars]ght'} != {u'field_type': u'assessor', u'static': False, u'checked': [169 chars]ght'}
  {u'checked': False,
   u'class': u'is_aligned_right',
-  u'field_type': u'building_information',
+  u'field_type': u'assessor',
+  u'is_extra_data': True,
-  u'link': True,
?           ^^^

+  u'link': False,
?           ^^^^

-  u'sort_column': u'address_line_1',
+  u'sort_column': u'AC Adjusted',
   u'sortable': True,
   u'static': False,
-  u'title': u'Address Line 1',
+  u'title': u'AC Adjusted',
   u'type': u'string'}

======================================================================
FAIL: Same endpoint.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/seed/seed/tests/test_views.py", line 1674, in test_save_column_mappings
    assert(eu_col.unit is not None)
AssertionError

----------------------------------------------------------------------
Ran 319 tests in 104.364s

FAILED (SKIP=3, failures=2)
```

**Comment by nllong** [comment]
Thanks Miles for getting this PR together. I'm not sure why your environment is failing. Since Travis is passing, I imagine that it is your environment.

**Comment by nllong** [comment]
We should close this PR and create a new one from the reorg-django18 so that we can add comments to the official PR that will be happening.

@mmclark I am seeing the same 2 test failures that you sent me. I will look into them.

**Comment by mmclark** [comment]
I agree that we should close this PR.  It might be good to address the 
two failing tests and then I can issue a new PR from reorg-django18.

thanks!

**Comment by nllong** [comment]
Deal. Do you want me to work directly on your branch on seed-platform or should I work on a fork?

- nick

**Comment by mmclark** [comment]
You can work directly on the branch.

**Comment by RDmitchell** [comment]
The reorg has been completed and is being tested in a branch. Any issues coming out of testing can be added to new issues, so I am closing this issue.

**Pull request closed without merging**
