### PR TITLE
Update the add_buildings task to use the appropriate search/filtering logic

### PR DESCRIPTION
**Pull request by pipermerriam**
Fixes issue #616

### What was broken?

The function `seed.tasks.add_buildings` did not use the same search/sort/filtering logic that other portions of the site use, as well as not handling the `select_all_checkbox` flag correctly.  This meant that the feature generally worked correctly except for cases where the select all checkbox was checked.

### How was it fixed.

Updated the task to use the same helper functions that are used elsewhere in the site (`seed.views.main.search_buildings` and the labeling functionality).  I added a basic unit test for this as well since this task didn't appear to have any test coverage.

#### Cute animal picture.

tumblr_mgthg3ferx1rhu60ro1_500

### CODE REVIEW

**Comment by RDmitchell** [comment]
Thanks Piper. I will see if Miles can get this merged to develop and onto seedtest tonight, so I can do some testing tomorrow !

**Comment by pipermerriam** [comment]
Ready when tests are passing

**Comment by mmclark** [comment]
Piper - is this ready to merge?  You removed the "DO NOT MERGE" label, but travis is failing on some tests.  What's the next step?  Thanks!

**Comment by nicholasserra** [comment]
Closing this PR and opening a new one.

**Pull request closed without merging**
